# Form implementation generated from reading ui file '.\ui_AboutTheProgram.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutTheProgram(object):
    def setupUi(self, AboutTheProgram):
        AboutTheProgram.setObjectName("AboutTheProgram")
        AboutTheProgram.resize(1448, 961)
        AboutTheProgram.setMinimumSize(QtCore.QSize(1280, 720))
        AboutTheProgram.setStyleSheet("*{\n"
"    color:white;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(AboutTheProgram)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(parent=AboutTheProgram)
        self.frame_12.setMaximumSize(QtCore.QSize(1280, 720))
        self.frame_12.setStyleSheet("*\n"
"{\n"
"    border: none;\n"
"     background-color:black;\n"
"    border-radius:30;\n"
"\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.slide_menu_container = QtWidgets.QFrame(parent=self.frame_12)
        self.slide_menu_container.setMinimumSize(QtCore.QSize(200, 0))
        self.slide_menu_container.setMaximumSize(QtCore.QSize(250, 16777215))
        self.slide_menu_container.setStyleSheet("")
        self.slide_menu_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.slide_menu_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.slide_menu_container.setObjectName("slide_menu_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.slide_menu_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(parent=self.slide_menu_container)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.logo_img = QtWidgets.QLabel(parent=self.frame_8)
        self.logo_img.setGeometry(QtCore.QRect(50, 0, 64, 64))
        self.logo_img.setText("")
        self.logo_img.setPixmap(QtGui.QPixmap(":/icon/image/icon/free-icon-letter-z-8061473 (1).png"))
        self.logo_img.setObjectName("logo_img")
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushDownload = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushDownload.setGeometry(QtCore.QRect(20, 10, 131, 131))
        self.pushDownload.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushDownload.setFont(font)
        self.pushDownload.setStyleSheet("QPushButton {\n"
"    background-color: #161A1E;\n"
"    color: white;\n"
"    border-radius: 65px; /* Уточним единицы измерения для радиуса */\n"
"    border: 4px solid #363538;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(115, 128, 142, 255);\n"
"    border: 4px solid white;\n"
"}\n"
"")
        self.pushDownload.setObjectName("pushDownload")
        self.pushSetting = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushSetting.setGeometry(QtCore.QRect(20, 170, 131, 131))
        self.pushSetting.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushSetting.setFont(font)
        self.pushSetting.setStyleSheet("QPushButton {\n"
"    background-color: #161A1E;\n"
"    color: white;\n"
"    border-radius: 65px; /* Уточним единицы измерения для радиуса */\n"
"    border: 4px solid #363538;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(115, 128, 142, 255);\n"
"    border: 4px solid white;\n"
"}\n"
"")
        self.pushSetting.setObjectName("pushSetting")
        self.pushActivate = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushActivate.setGeometry(QtCore.QRect(20, 350, 131, 131))
        self.pushActivate.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushActivate.setFont(font)
        self.pushActivate.setStyleSheet("QPushButton {\n"
"    background-color: #161A1E;\n"
"    color: white;\n"
"    border-radius: 65px; /* Уточним единицы измерения для радиуса */\n"
"    border: 4px solid #363538;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(115, 128, 142, 255);\n"
"    border: 4px solid white;\n"
"}\n"
"")
        self.pushActivate.setObjectName("pushActivate")
        self.verticalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout_11.addWidget(self.slide_menu_container)
        self.main_body = QtWidgets.QFrame(parent=self.frame_12)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(parent=self.main_body)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 60))
        self.header_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(parent=self.header_frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_3 = QtWidgets.QFrame(parent=self.header_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setStyleSheet("*{\n"
"    margin-left:2px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(parent=self.header_frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame = QtWidgets.QFrame(parent=self.header_frame)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setStyleSheet("*\n"
"{\n"
"    margin-left:6px;\n"
"}\n"
"QPushButton#pushClose{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushClose:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushClose:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushCollapse{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushCollapse:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushCollapse:pressed{\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushUnwrap{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUnwrap:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUnwrap:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushCollapse = QtWidgets.QPushButton(parent=self.frame)
        self.pushCollapse.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/image/icon/free-icon-minimize-4889317.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushCollapse.setIcon(icon)
        self.pushCollapse.setIconSize(QtCore.QSize(32, 32))
        self.pushCollapse.setObjectName("pushCollapse")
        self.horizontalLayout_4.addWidget(self.pushCollapse)
        self.pushUnwrap = QtWidgets.QPushButton(parent=self.frame)
        self.pushUnwrap.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/image/icon/free-icon-expand-510829.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushUnwrap.setIcon(icon1)
        self.pushUnwrap.setIconSize(QtCore.QSize(25, 25))
        self.pushUnwrap.setObjectName("pushUnwrap")
        self.horizontalLayout_4.addWidget(self.pushUnwrap)
        self.pushClose = QtWidgets.QPushButton(parent=self.frame)
        self.pushClose.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/image/icon/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushClose.setIcon(icon2)
        self.pushClose.setIconSize(QtCore.QSize(32, 32))
        self.pushClose.setObjectName("pushClose")
        self.horizontalLayout_4.addWidget(self.pushClose)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout.addWidget(self.header_frame)
        self.main_body_contents = QtWidgets.QFrame(parent=self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_contents.sizePolicy().hasHeightForWidth())
        self.main_body_contents.setSizePolicy(sizePolicy)
        self.main_body_contents.setStyleSheet("body {\n"
"  margin: 0;\n"
"  background: #F4EDE5;\n"
"}\n"
"div {\n"
"  width: 100px;\n"
"  height: 100px;\n"
"  transform: translate(-50%, -50%);\n"
"  position: absolute; \n"
"  top: 50%; \n"
"  left: 50%;\n"
"}\n"
"span {\n"
"  display: block;\n"
"  position: absolute;\n"
"  width: 40%;\n"
"  height: 40%;\n"
"  border-radius: 50%;\n"
"  box-shadow: 2px 2px 3px rgba(0,0,0,.4);\n"
"  -webkit-animation: run 2s infinite ease-in-out;\n"
"  animation: run 2s infinite ease-in-out;\n"
"}\n"
"\n"
".one {\n"
"  background: #F3B222;\n"
"  -webkit-animation-delay: 1.5s;\n"
"  animation-delay: 1.5s;\n"
"}\n"
".two {\n"
"  background: #F0653E;\n"
"  -webkit-animation-delay: 1s;\n"
"  animation-delay: 1s;\n"
"}\n"
".three {\n"
"  background: #B9C0C0;\n"
"  -webkit-animation-delay: 0.5s;\n"
"  animation-delay: 0.5s;\n"
"}\n"
".four {\n"
"  background: #8F7473;\n"
"}\n"
"\n"
"@-webkit-keyframes run {\n"
"  0% {\n"
"    transform: translate(0%);\n"
"    border-radius: 50%;\n"
"  }\n"
"  25% {\n"
"    transform: translate(150%) scale(0.5); \n"
"    border-radius: 0%;\n"
"  }\n"
"  50% {\n"
"    transform: translate(150%, 150%);\n"
"    border-radius: 50%; \n"
"  }\n"
"  75% {\n"
"    transform: translate(0%, 150%) scale(0.5); \n"
"    border-radius: 0%;\n"
"  }\n"
"}\n"
"@keyframes run {\n"
"  0% {\n"
"    transform: translate(0%);\n"
"    border-radius: 50%;\n"
"  }\n"
"  25% {\n"
"    transform: translate(150%) scale(0.5); \n"
"    border-radius: 0%;\n"
"  }\n"
"  50% {\n"
"    transform: translate(150%, 150%);\n"
"    border-radius: 50%; \n"
"  }\n"
"  75% {\n"
"    transform: translate(0%, 150%) scale(0.5); \n"
"    border-radius: 0%;\n"
"  }\n"
"}")
        self.main_body_contents.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_body_contents.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_body_contents.setObjectName("main_body_contents")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.main_body_contents)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_13 = QtWidgets.QFrame(parent=self.main_body_contents)
        self.frame_13.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.widget = QtWidgets.QWidget(parent=self.frame_13)
        self.widget.setGeometry(QtCore.QRect(10, 10, 501, 281))
        self.widget.setStyleSheet("QPushButton#pushDownloadUpdate{\n"
"background-color: #161A1E;\n"
"border: none;\n"
"     \n"
"    border-radius:30;\n"
"}")
        self.widget.setObjectName("widget")
        self.infProgram = QtWidgets.QTextEdit(parent=self.widget)
        self.infProgram.setGeometry(QtCore.QRect(10, 30, 451, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infProgram.setFont(font)
        self.infProgram.setStyleSheet("*{\n"
"color:silver;\n"
"\n"
"}")
        self.infProgram.setObjectName("infProgram")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("*{\n"
"color:rgb(85, 255, 255);\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushDownloadUpdate = QtWidgets.QPushButton(parent=self.widget)
        self.pushDownloadUpdate.setGeometry(QtCore.QRect(310, 192, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushDownloadUpdate.setFont(font)
        self.pushDownloadUpdate.setStyleSheet("border-radius:15;")
        self.pushDownloadUpdate.setObjectName("pushDownloadUpdate")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_11.setGeometry(QtCore.QRect(490, 10, 481, 441))
        self.frame_11.setMaximumSize(QtCore.QSize(481, 441))
        self.frame_11.setStyleSheet("*{    \n"
"    color:silver;\n"
"    background-color:#161A1E;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_11)
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #161A1E;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #34373b;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:#161A1E;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #161A1E;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(0, 39, 461, 781))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(1380, 800))
        self.textEdit.setStyleSheet("*{\n"
"    color:silver;\n"
"\n"
"    background-color:#161A1E;\n"
"    padding:10px;\n"
"    \n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_14.setGeometry(QtCore.QRect(750, 510, 120, 80))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_15.setGeometry(QtCore.QRect(520, 470, 451, 131))
        self.frame_15.setStyleSheet("QPushButton#pushUrlDiscord{\n"
"    background-color:#161A1E;\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUrlDiscord:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUrlDiscord:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushUrlGitHub{\n"
"    background-color:#161A1E;\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUrlGitHub:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUrlGitHub:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushUrlFacebook{\n"
"    background-color:#161A1E;\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUrlFacebook:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUrlFacebook:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushUrlYouTube{\n"
"    background-color:#161A1E;\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUrlYouTube:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUrlYouTubek:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushButtonProfile:hover {\n"
"    height: 131px;\n"
"    color:rgba(115,128,142,255);\n"
"}\n"
"QPushButton#pushButtonSubPrmium:hover {\n"
"color:rgba(115,128,142,255);\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.pushUrlDiscord = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushUrlDiscord.setGeometry(QtCore.QRect(20, 70, 51, 51))
        self.pushUrlDiscord.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(21)
        self.pushUrlDiscord.setFont(font)
        self.pushUrlDiscord.setStyleSheet("border-radius:25;")
        self.pushUrlDiscord.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/image/icon/free-icon-discord-2626288.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushUrlDiscord.setIcon(icon3)
        self.pushUrlDiscord.setIconSize(QtCore.QSize(51, 51))
        self.pushUrlDiscord.setObjectName("pushUrlDiscord")
        self.pushUrlGitHub = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushUrlGitHub.setGeometry(QtCore.QRect(80, 70, 51, 51))
        self.pushUrlGitHub.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(21)
        self.pushUrlGitHub.setFont(font)
        self.pushUrlGitHub.setStyleSheet("border-radius:25;")
        self.pushUrlGitHub.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/image/icon/free-icon-github-733553 (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushUrlGitHub.setIcon(icon4)
        self.pushUrlGitHub.setIconSize(QtCore.QSize(51, 51))
        self.pushUrlGitHub.setObjectName("pushUrlGitHub")
        self.pushUrlFacebook = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushUrlFacebook.setGeometry(QtCore.QRect(140, 70, 51, 51))
        self.pushUrlFacebook.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(21)
        self.pushUrlFacebook.setFont(font)
        self.pushUrlFacebook.setStyleSheet("border-radius:25;")
        self.pushUrlFacebook.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/image/icon/facebook_logo_icon_147291.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushUrlFacebook.setIcon(icon5)
        self.pushUrlFacebook.setIconSize(QtCore.QSize(51, 51))
        self.pushUrlFacebook.setObjectName("pushUrlFacebook")
        self.pushUrlYouTube = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushUrlYouTube.setGeometry(QtCore.QRect(200, 70, 51, 51))
        self.pushUrlYouTube.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(21)
        self.pushUrlYouTube.setFont(font)
        self.pushUrlYouTube.setStyleSheet("border-radius:25;")
        self.pushUrlYouTube.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/image/icon/1491580651-yumminkysocialmedia28_83061.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushUrlYouTube.setIcon(icon6)
        self.pushUrlYouTube.setIconSize(QtCore.QSize(51, 51))
        self.pushUrlYouTube.setObjectName("pushUrlYouTube")
        self.pushButtonProfile = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushButtonProfile.setGeometry(QtCore.QRect(10, 10, 251, 51))
        self.pushButtonProfile.setMinimumSize(QtCore.QSize(0, 51))
        self.pushButtonProfile.setMaximumSize(QtCore.QSize(16777215, 111))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonProfile.setFont(font)
        self.pushButtonProfile.setStyleSheet("background-color: #161A1E;\n"
"border-radius:25px;")
        self.pushButtonProfile.setObjectName("pushButtonProfile")
        self.label_ProfileLogo = QtWidgets.QLabel(parent=self.frame_15)
        self.label_ProfileLogo.setGeometry(QtCore.QRect(110, 20, 47, 13))
        self.label_ProfileLogo.setStyleSheet("background-color: transparent;\n"
"color:transparent;")
        self.label_ProfileLogo.setObjectName("label_ProfileLogo")
        self.label_ProfileName = QtWidgets.QLabel(parent=self.frame_15)
        self.label_ProfileName.setGeometry(QtCore.QRect(20, 40, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ProfileName.setFont(font)
        self.label_ProfileName.setStyleSheet("background-color: transparent;\n"
"color:transparent;")
        self.label_ProfileName.setObjectName("label_ProfileName")
        self.label_ProfileEmail = QtWidgets.QLabel(parent=self.frame_15)
        self.label_ProfileEmail.setGeometry(QtCore.QRect(20, 60, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ProfileEmail.setFont(font)
        self.label_ProfileEmail.setStyleSheet("background-color: transparent;\n"
"color:transparent;")
        self.label_ProfileEmail.setObjectName("label_ProfileEmail")
        self.label_ProfileSub = QtWidgets.QLabel(parent=self.frame_15)
        self.label_ProfileSub.setGeometry(QtCore.QRect(20, 80, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ProfileSub.setFont(font)
        self.label_ProfileSub.setStyleSheet("background-color: transparent;\n"
"color:transparent;")
        self.label_ProfileSub.setObjectName("label_ProfileSub")
        self.label_EnterProfileName = QtWidgets.QLabel(parent=self.frame_15)
        self.label_EnterProfileName.setGeometry(QtCore.QRect(80, 40, 161, 16))
        self.label_EnterProfileName.setStyleSheet("background-color: transparent;\n"
"color:transparent;")
        self.label_EnterProfileName.setText("")
        self.label_EnterProfileName.setObjectName("label_EnterProfileName")
        self.label_EnterProfileEmail = QtWidgets.QLabel(parent=self.frame_15)
        self.label_EnterProfileEmail.setGeometry(QtCore.QRect(80, 60, 161, 16))
        self.label_EnterProfileEmail.setStyleSheet("background-color: transparent;\n"
"color:transparent;")
        self.label_EnterProfileEmail.setText("")
        self.label_EnterProfileEmail.setObjectName("label_EnterProfileEmail")
        self.label_EnterProfileSub = QtWidgets.QLabel(parent=self.frame_15)
        self.label_EnterProfileSub.setGeometry(QtCore.QRect(80, 80, 151, 16))
        self.label_EnterProfileSub.setStyleSheet("background-color: transparent;\n"
"color:transparent;")
        self.label_EnterProfileSub.setText("")
        self.label_EnterProfileSub.setObjectName("label_EnterProfileSub")
        self.pushInf = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushInf.setGeometry(QtCore.QRect(280, 10, 50, 50))
        self.pushInf.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushInf.setFont(font)
        self.pushInf.setStyleSheet("\n"
"QPushButton {\n"
"background-color: #161A1E;\n"
"color:white;\n"
"border-radius:25;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgba(115,128,142,255);\n"
"}")
        self.pushInf.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/image/icon/information.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushInf.setIcon(icon7)
        self.pushInf.setIconSize(QtCore.QSize(50, 50))
        self.pushInf.setObjectName("pushInf")
        self.pushButtonSubPrmium = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushButtonSubPrmium.setGeometry(QtCore.QRect(40, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSubPrmium.setFont(font)
        self.pushButtonSubPrmium.setStyleSheet("background-color: transparent;\n"
"color:transparent;")
        self.pushButtonSubPrmium.setObjectName("pushButtonSubPrmium")
        self.pushExit = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushExit.setGeometry(QtCore.QRect(350, 60, 100, 61))
        self.pushExit.setMinimumSize(QtCore.QSize(100, 50))
        self.pushExit.setMaximumSize(QtCore.QSize(200, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushExit.setFont(font)
        self.pushExit.setStyleSheet("QPushButton {\n"
"background-color: #161A1E;\n"
"color:white;\n"
"border-radius:25;\n"
"}\n"
"QPushButton:hover {\n"
"color:rgba(115,128,142,255);\n"
"}")
        self.pushExit.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/image/icon/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushExit.setIcon(icon8)
        self.pushExit.setIconSize(QtCore.QSize(30, 30))
        self.pushExit.setObjectName("pushExit")
        self.label = QtWidgets.QLabel(parent=self.frame_15)
        self.label.setGeometry(QtCore.QRect(350, 10, 91, 41))
        self.label.setStyleSheet("background-color: #161A1E;\n"
"color:white;\n"
"border-radius: 20px;\n"
"")
        self.label.setObjectName("label")
        self.UpBar = QtWidgets.QWidget(parent=self.frame_13)
        self.UpBar.setGeometry(QtCore.QRect(-271, -81, 1141, 91))
        self.UpBar.setObjectName("UpBar")
        self.horizontalLayout_12.addWidget(self.frame_13)
        self.verticalLayout.addWidget(self.main_body_contents)
        self.footer = QtWidgets.QFrame(parent=self.main_body)
        self.footer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(parent=self.footer)
        self.frame_4.setStyleSheet("*{\n"
"    color:white;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.footer)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.size_grip = QtWidgets.QFrame(parent=self.footer)
        self.size_grip.setMinimumSize(QtCore.QSize(10, 10))
        self.size_grip.setMaximumSize(QtCore.QSize(0, 0))
        self.size_grip.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.size_grip.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.size_grip.setObjectName("size_grip")
        self.horizontalLayout_3.addWidget(self.size_grip, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout.addWidget(self.footer, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout_11.addWidget(self.main_body)
        self.horizontalLayout.addWidget(self.frame_12)

        self.retranslateUi(AboutTheProgram)
        QtCore.QMetaObject.connectSlotsByName(AboutTheProgram)

    def retranslateUi(self, AboutTheProgram):
        _translate = QtCore.QCoreApplication.translate
        AboutTheProgram.setWindowTitle(_translate("AboutTheProgram", "Form"))
        self.pushDownload.setText(_translate("AboutTheProgram", "SOFT"))
        self.pushSetting.setText(_translate("AboutTheProgram", "SETTINGS"))
        self.pushActivate.setText(_translate("AboutTheProgram", "ACTIVATE"))
        self.infProgram.setHtml(_translate("AboutTheProgram", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ZoomApp - оптимизирует и активрует твой пк, а также и установит нужный софт. Безопасно, можно и быстро. Повышает быстродействие и ФПС во всех играх и уменьшает системную задержку до минимально возможной!</p></body></html>"))
        self.label_2.setText(_translate("AboutTheProgram", "Доступные обновления"))
        self.pushDownloadUpdate.setText(_translate("AboutTheProgram", "Скачать"))
        self.textEdit.setHtml(_translate("AboutTheProgram", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">2.03.2023</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">-В коде добавил папку с класами</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">-Изменил скачивание приложения, но без установки</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">-Изменил скрол на главной странице и у функциональной кнопки Установить</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">1.03.2023</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">- Добавлен метод регистрации с всеми возможными проверками</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">- Добавленно 3 виджета</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">- Добавленна база данных</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">- Исправлен баг с регистрацией</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">- Добавленно 3 кнопки Установка, Настройка, Активация</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">- Переработано основное меню</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">- Добален лейбл о приложении</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">- И добавлен текст с последними изменениями</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">-Добавил функционал кнопки Установить</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">- Создал новый клас в котором будут устанавливаться приложения  при нажатии на кнопку </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("AboutTheProgram", "Последнее обновления:"))
        self.pushButtonProfile.setText(_translate("AboutTheProgram", "Profile"))
        self.label_ProfileLogo.setText(_translate("AboutTheProgram", "Profile"))
        self.label_ProfileName.setText(_translate("AboutTheProgram", "Name:"))
        self.label_ProfileEmail.setText(_translate("AboutTheProgram", "Email:"))
        self.label_ProfileSub.setText(_translate("AboutTheProgram", "Sub:"))
        self.pushButtonSubPrmium.setText(_translate("AboutTheProgram", "Free"))
        self.label.setText(_translate("AboutTheProgram", "      alpfa 0.33"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutTheProgram = QtWidgets.QWidget()
    ui = Ui_AboutTheProgram()
    ui.setupUi(AboutTheProgram)
    AboutTheProgram.show()
    sys.exit(app.exec())
