# Form implementation generated from reading ui file '.\ui_BackUp.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BackUp(object):
    def setupUi(self, BackUp):
        BackUp.setObjectName("BackUp")
        BackUp.resize(1511, 836)
        BackUp.setMinimumSize(QtCore.QSize(1280, 720))
        BackUp.setStyleSheet("*{\n"
"    color:white;\n"
"    \n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(BackUp)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(parent=BackUp)
        self.frame_12.setMaximumSize(QtCore.QSize(1280, 720))
        self.frame_12.setStyleSheet("*\n"
"{\n"
"    border: none;\n"
"     background-color:black;\n"
"    border-radius:30;\n"
"    color:black\n"
"    \n"
"\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_2.setStyleSheet("background:black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_2)
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: black;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #34373b;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:black;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: black;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1244, 684))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1000, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushBackMenu = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushBackMenu.setGeometry(QtCore.QRect(1130, 40, 61, 61))
        self.pushBackMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.pushBackMenu.setStyleSheet("QPushButton#pushBackMenu\n"
"{\n"
"background-color:#161A1E;\n"
"}\n"
"QPushButton#pushBackMenu:hover\n"
"{\n"
"background-color:white;\n"
"}\n"
"")
        self.pushBackMenu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\image/icon/back-left-arrow-circular-button-outline.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushBackMenu.setIcon(icon)
        self.pushBackMenu.setIconSize(QtCore.QSize(63, 63))
        self.pushBackMenu.setObjectName("pushBackMenu")
        self.frame = QtWidgets.QFrame(parent=self.frame_4)
        self.frame.setGeometry(QtCore.QRect(1070, -10, 140, 50))
        self.frame.setMinimumSize(QtCore.QSize(140, 40))
        self.frame.setMaximumSize(QtCore.QSize(140, 50))
        self.frame.setStyleSheet("*\n"
"{\n"
"    margin-left:6px;\n"
"}\n"
"QPushButton#pushClose{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushClose:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushClose:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushCollapse{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushCollapse:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushCollapse:pressed{\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushUnwrap{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUnwrap:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUnwrap:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushCollapse = QtWidgets.QPushButton(parent=self.frame)
        self.pushCollapse.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/image/icon/free-icon-minimize-4889317.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushCollapse.setIcon(icon1)
        self.pushCollapse.setIconSize(QtCore.QSize(32, 32))
        self.pushCollapse.setObjectName("pushCollapse")
        self.horizontalLayout_8.addWidget(self.pushCollapse)
        self.pushUnwrap = QtWidgets.QPushButton(parent=self.frame)
        self.pushUnwrap.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/image/icon/free-icon-expand-510829.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushUnwrap.setIcon(icon2)
        self.pushUnwrap.setIconSize(QtCore.QSize(25, 25))
        self.pushUnwrap.setObjectName("pushUnwrap")
        self.horizontalLayout_8.addWidget(self.pushUnwrap)
        self.pushClose = QtWidgets.QPushButton(parent=self.frame)
        self.pushClose.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/image/icon/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushClose.setIcon(icon3)
        self.pushClose.setIconSize(QtCore.QSize(32, 32))
        self.pushClose.setObjectName("pushClose")
        self.horizontalLayout_8.addWidget(self.pushClose)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(520, 10, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"    color:white;\n"
"\n"
"    padding: 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 20px;\n"
"    margin: 4px 2px;\n"
"  text-transform: uppercase;\n"
"  letter-spacing: 1.3px;\n"
"  font-weight: 700;\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.Soft = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.Soft.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Soft.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Soft.setObjectName("Soft")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Soft)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.Soft)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Profile = QtWidgets.QFrame(parent=self.frame_3)
        self.Profile.setGeometry(QtCore.QRect(10, 20, 1201, 61))
        self.Profile.setStyleSheet("*{\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.Profile.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Profile.setObjectName("Profile")
        self.pushCreateProfile = QtWidgets.QPushButton(parent=self.Profile)
        self.pushCreateProfile.setGeometry(QtCore.QRect(10, 10, 200, 40))
        self.pushCreateProfile.setMinimumSize(QtCore.QSize(200, 40))
        self.pushCreateProfile.setMaximumSize(QtCore.QSize(91, 31))
        self.pushCreateProfile.setBaseSize(QtCore.QSize(0, 0))
        self.pushCreateProfile.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(38, 23, 255);\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-weight: bold;\n"
"    font-size: 14px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(168, 168, 168);\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushCreateProfile.setObjectName("pushCreateProfile")
        self.pushImportProfile = QtWidgets.QPushButton(parent=self.Profile)
        self.pushImportProfile.setGeometry(QtCore.QRect(230, 10, 200, 40))
        self.pushImportProfile.setMinimumSize(QtCore.QSize(200, 40))
        self.pushImportProfile.setMaximumSize(QtCore.QSize(91, 31))
        self.pushImportProfile.setBaseSize(QtCore.QSize(0, 0))
        self.pushImportProfile.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 14px; /* Установите размер шрифта */\n"
"    font-weight: bold;\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushImportProfile.setObjectName("pushImportProfile")
        self.pushUpdateProfile = QtWidgets.QPushButton(parent=self.Profile)
        self.pushUpdateProfile.setGeometry(QtCore.QRect(990, 10, 200, 40))
        self.pushUpdateProfile.setMinimumSize(QtCore.QSize(200, 40))
        self.pushUpdateProfile.setMaximumSize(QtCore.QSize(91, 31))
        self.pushUpdateProfile.setBaseSize(QtCore.QSize(0, 0))
        self.pushUpdateProfile.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 14px; /* Установите размер шрифта */\n"
"    font-weight: bold;\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushUpdateProfile.setObjectName("pushUpdateProfile")
        self.pushDelProfile = QtWidgets.QPushButton(parent=self.Profile)
        self.pushDelProfile.setGeometry(QtCore.QRect(770, 10, 200, 40))
        self.pushDelProfile.setMinimumSize(QtCore.QSize(200, 40))
        self.pushDelProfile.setMaximumSize(QtCore.QSize(91, 31))
        self.pushDelProfile.setBaseSize(QtCore.QSize(0, 0))
        self.pushDelProfile.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 14px; /* Установите размер шрифта */\n"
"    font-weight: bold;\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushDelProfile.setObjectName("pushDelProfile")
        self.pushBackUp = QtWidgets.QPushButton(parent=self.Profile)
        self.pushBackUp.setGeometry(QtCore.QRect(480, 10, 220, 40))
        self.pushBackUp.setMinimumSize(QtCore.QSize(220, 40))
        self.pushBackUp.setMaximumSize(QtCore.QSize(91, 31))
        self.pushBackUp.setBaseSize(QtCore.QSize(0, 0))
        self.pushBackUp.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(38, 23, 255);\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-weight: bold;\n"
"    font-size: 14px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(168, 168, 168);\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushBackUp.setObjectName("pushBackUp")
        self.label_local = QtWidgets.QLabel(parent=self.frame_3)
        self.label_local.setGeometry(QtCore.QRect(480, 110, 201, 71))
        self.label_local.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"    color:white;\n"
"\n"
"    padding: 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 20px;\n"
"    margin: 4px 2px;\n"
"  text-transform: uppercase;\n"
"  letter-spacing: 1.3px;\n"
"  font-weight: 700;\n"
"\n"
"")
        self.label_local.setObjectName("label_local")
        self.frame_BackUp = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_BackUp.setGeometry(QtCore.QRect(10, 210, 1211, 71))
        self.frame_BackUp.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_BackUp.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_BackUp.setObjectName("frame_BackUp")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.Soft)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_11.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame_12)

        self.retranslateUi(BackUp)
        QtCore.QMetaObject.connectSlotsByName(BackUp)

    def retranslateUi(self, BackUp):
        _translate = QtCore.QCoreApplication.translate
        BackUp.setWindowTitle(_translate("BackUp", "Form"))
        self.label_3.setText(_translate("BackUp", "BackUp"))
        self.pushCreateProfile.setText(_translate("BackUp", "Сделать снимок"))
        self.pushImportProfile.setText(_translate("BackUp", "Импорт файла"))
        self.pushUpdateProfile.setText(_translate("BackUp", "Обновить"))
        self.pushDelProfile.setText(_translate("BackUp", "Удалить"))
        self.pushBackUp.setText(_translate("BackUp", "Резервное копирование"))
        self.label_local.setText(_translate("BackUp", "Локальный"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BackUp = QtWidgets.QWidget()
    ui = Ui_BackUp()
    ui.setupUi(BackUp)
    BackUp.show()
    sys.exit(app.exec())
