# Form implementation generated from reading ui file '.\ui_reg.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Ui_Reg(object):
    def setupUi(self, Ui_Reg):
        Ui_Reg.setObjectName("Ui_Reg")
        Ui_Reg.resize(372, 481)
        font = QtGui.QFont()
        font.setPointSize(9)
        Ui_Reg.setFont(font)
        Ui_Reg.setStyleSheet("border-radius:25px;")
        self.widget = QtWidgets.QWidget(parent=Ui_Reg)
        self.widget.setGeometry(QtCore.QRect(0, 0, 370, 480))
        self.widget.setStyleSheet("QPushButton#pushLogin{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:20;\n"
"}\n"
"QPushButton#pushLogin:hover{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#pushLogin:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105,118,132,200);\n"
"}\n"
"QPushButton#pushReg{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:20;\n"
"}\n"
"QPushButton#pushReg:hover{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#pushReg:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105,118,132,200);\n"
"}\n"
"QPushButton#pushUrlDiscord{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUrlDiscord:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUrlDiscord:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushUrlGitHub{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUrlGitHub:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUrlGitHub:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushUrlFacebook{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUrlFacebook:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUrlFacebook:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushUrlYouTube{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushUrlYouTube:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushUrlYouTubek:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"QPushButton#pushClose{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushClose:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushClose:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"\n"
"QPushButton#pushBack{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(85,98,112,255);\n"
"}\n"
"QPushButton#pushBack:hover{\n"
"    color:rgba(155,168,182,220);\n"
"}\n"
"QPushButton#pushBack:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(115,128,142,255)\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 300, 420))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setStyleSheet("border-image:url(:/image/image/photo/login.jpg);\n"
"border-radius:20px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Password = QtWidgets.QLineEdit(parent=self.widget)
        self.Password.setGeometry(QtCore.QRect(90, 200, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password.setFont(font)
        self.Password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(108,118,132,255);\n"
"color:rgba(255,255,255,230);\n"
"pading-bottom:7px;")
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password.setObjectName("Password")
        self.pushClose = QtWidgets.QPushButton(parent=self.widget)
        self.pushClose.setGeometry(QtCore.QRect(300, 40, 30, 30))
        self.pushClose.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Symbol")
        font.setPointSize(22)
        self.pushClose.setFont(font)
        self.pushClose.setObjectName("pushClose")
        self.pushReg = QtWidgets.QPushButton(parent=self.widget)
        self.pushReg.setGeometry(QtCore.QRect(90, 350, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushReg.setFont(font)
        self.pushReg.setObjectName("pushReg")
        self.ConfirmPassword = QtWidgets.QLineEdit(parent=self.widget)
        self.ConfirmPassword.setGeometry(QtCore.QRect(90, 250, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ConfirmPassword.setFont(font)
        self.ConfirmPassword.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(108,118,132,255);\n"
"color:rgba(255,255,255,230);\n"
"pading-bottom:7px;")
        self.ConfirmPassword.setText("")
        self.ConfirmPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ConfirmPassword.setObjectName("ConfirmPassword")
        self.FirstName = QtWidgets.QLineEdit(parent=self.widget)
        self.FirstName.setGeometry(QtCore.QRect(90, 120, 71, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FirstName.setFont(font)
        self.FirstName.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(108,118,132,255);\n"
"color:rgba(255,255,255,230);\n"
"pading-bottom:7px;")
        self.FirstName.setObjectName("FirstName")
        self.LastName = QtWidgets.QLineEdit(parent=self.widget)
        self.LastName.setGeometry(QtCore.QRect(190, 120, 91, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LastName.setFont(font)
        self.LastName.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(108,118,132,255);\n"
"color:rgba(255,255,255,230);\n"
"pading-bottom:7px;")
        self.LastName.setObjectName("LastName")
        self.Email = QtWidgets.QLineEdit(parent=self.widget)
        self.Email.setGeometry(QtCore.QRect(90, 160, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Email.setFont(font)
        self.Email.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(108,118,132,255);\n"
"color:rgba(255,255,255,230);\n"
"pading-bottom:7px;")
        self.Email.setObjectName("Email")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(90, 310, 201, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushBack = QtWidgets.QPushButton(parent=self.widget)
        self.pushBack.setGeometry(QtCore.QRect(50, 50, 30, 30))
        self.pushBack.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(22)
        self.pushBack.setFont(font)
        self.pushBack.setObjectName("pushBack")
        self.UpBar = QtWidgets.QWidget(parent=self.widget)
        self.UpBar.setGeometry(QtCore.QRect(79, 40, 221, 41))
        self.UpBar.setObjectName("UpBar")

        self.retranslateUi(Ui_Reg)
        QtCore.QMetaObject.connectSlotsByName(Ui_Reg)

    def retranslateUi(self, Ui_Reg):
        _translate = QtCore.QCoreApplication.translate
        Ui_Reg.setWindowTitle(_translate("Ui_Reg", "Dialog"))
        self.Password.setPlaceholderText(_translate("Ui_Reg", "Password"))
        self.pushClose.setText(_translate("Ui_Reg", "´"))
        self.pushReg.setText(_translate("Ui_Reg", "Registation"))
        self.ConfirmPassword.setPlaceholderText(_translate("Ui_Reg", "Confirm Password"))
        self.FirstName.setPlaceholderText(_translate("Ui_Reg", "First Name"))
        self.LastName.setPlaceholderText(_translate("Ui_Reg", "Last Name"))
        self.Email.setPlaceholderText(_translate("Ui_Reg", "Email"))
        self.pushBack.setText(_translate("Ui_Reg", "〱"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_Reg = QtWidgets.QDialog()
    ui = Ui_Ui_Reg()
    ui.setupUi(Ui_Reg)
    Ui_Reg.show()
    sys.exit(app.exec())
