# Form implementation generated from reading ui file '.\BaseSettings.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BaseSettings(object):
    def setupUi(self, BaseSettings):
        BaseSettings.setObjectName("BaseSettings")
        BaseSettings.resize(1114, 576)
        BaseSettings.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(parent=BaseSettings)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1015, 602))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(820, 20, 120, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 971, 581))
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
"*{\n"
"margin:0\n"
"\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #161A1E;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #34373b;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:#161A1E;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #161A1E;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 955, 670))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 670))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(10, 50, 941, 581))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_MouseAcceleration = QtWidgets.QFrame(parent=self.frame)
        self.frame_MouseAcceleration.setGeometry(QtCore.QRect(10, 10, 900, 45))
        self.frame_MouseAcceleration.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_MouseAcceleration.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_MouseAcceleration.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_MouseAcceleration {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_MouseAcceleration.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_MouseAcceleration.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_MouseAcceleration.setObjectName("frame_MouseAcceleration")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_MouseAcceleration)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_1 = QtWidgets.QFrame(parent=self.frame_MouseAcceleration)
        self.frame_1.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_1.setStyleSheet("background-color: transparent;")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_1.setObjectName("frame_1")
        self.pushMouseAcceleration = QtWidgets.QPushButton(parent=self.frame_1)
        self.pushMouseAcceleration.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushMouseAcceleration.setMinimumSize(QtCore.QSize(91, 31))
        self.pushMouseAcceleration.setMaximumSize(QtCore.QSize(91, 31))
        self.pushMouseAcceleration.setBaseSize(QtCore.QSize(0, 0))
        self.pushMouseAcceleration.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushMouseAcceleration.setObjectName("pushMouseAcceleration")
        self.labelTextMouseAcceleration = QtWidgets.QLabel(parent=self.frame_1)
        self.labelTextMouseAcceleration.setGeometry(QtCore.QRect(30, 10, 151, 21))
        self.labelTextMouseAcceleration.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextMouseAcceleration.setObjectName("labelTextMouseAcceleration")
        self.labelMouseAcceleration = QtWidgets.QLabel(parent=self.frame_1)
        self.labelMouseAcceleration.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelMouseAcceleration.setText("")
        self.labelMouseAcceleration.setObjectName("labelMouseAcceleration")
        self.horizontalLayout.addWidget(self.frame_1)
        self.frame_ProtectionNotifications = QtWidgets.QFrame(parent=self.frame)
        self.frame_ProtectionNotifications.setGeometry(QtCore.QRect(10, 61, 900, 45))
        self.frame_ProtectionNotifications.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_ProtectionNotifications.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_ProtectionNotifications.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_ProtectionNotifications {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_ProtectionNotifications.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ProtectionNotifications.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ProtectionNotifications.setObjectName("frame_ProtectionNotifications")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_ProtectionNotifications)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_ProtectionNotifications)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setStyleSheet("background-color: transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushProtectionNotifications = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushProtectionNotifications.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushProtectionNotifications.setMinimumSize(QtCore.QSize(91, 31))
        self.pushProtectionNotifications.setMaximumSize(QtCore.QSize(91, 31))
        self.pushProtectionNotifications.setBaseSize(QtCore.QSize(0, 0))
        self.pushProtectionNotifications.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushProtectionNotifications.setObjectName("pushProtectionNotifications")
        self.labelTextProtectionNotifications = QtWidgets.QLabel(parent=self.frame_2)
        self.labelTextProtectionNotifications.setGeometry(QtCore.QRect(30, 10, 201, 21))
        self.labelTextProtectionNotifications.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextProtectionNotifications.setObjectName("labelTextProtectionNotifications")
        self.labelProtectionNotifications = QtWidgets.QLabel(parent=self.frame_2)
        self.labelProtectionNotifications.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelProtectionNotifications.setText("")
        self.labelProtectionNotifications.setObjectName("labelProtectionNotifications")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_AutoUpdateDriversatSystemstartup = QtWidgets.QFrame(parent=self.frame)
        self.frame_AutoUpdateDriversatSystemstartup.setGeometry(QtCore.QRect(10, 112, 900, 45))
        self.frame_AutoUpdateDriversatSystemstartup.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_AutoUpdateDriversatSystemstartup.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_AutoUpdateDriversatSystemstartup.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_AutoUpdateDriversatSystemstartup {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_AutoUpdateDriversatSystemstartup.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AutoUpdateDriversatSystemstartup.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AutoUpdateDriversatSystemstartup.setObjectName("frame_AutoUpdateDriversatSystemstartup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_AutoUpdateDriversatSystemstartup)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_AutoUpdateDriversatSystemstartup)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setStyleSheet("background-color: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushAutoUpdateDriversatSystemstartup = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushAutoUpdateDriversatSystemstartup.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushAutoUpdateDriversatSystemstartup.setMinimumSize(QtCore.QSize(91, 31))
        self.pushAutoUpdateDriversatSystemstartup.setMaximumSize(QtCore.QSize(91, 31))
        self.pushAutoUpdateDriversatSystemstartup.setBaseSize(QtCore.QSize(0, 0))
        self.pushAutoUpdateDriversatSystemstartup.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushAutoUpdateDriversatSystemstartup.setObjectName("pushAutoUpdateDriversatSystemstartup")
        self.labelTextAutoUpdateDriversatSystemstartup = QtWidgets.QLabel(parent=self.frame_3)
        self.labelTextAutoUpdateDriversatSystemstartup.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextAutoUpdateDriversatSystemstartup.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextAutoUpdateDriversatSystemstartup.setObjectName("labelTextAutoUpdateDriversatSystemstartup")
        self.labelAutoUpdateDriversatSystemstartup = QtWidgets.QLabel(parent=self.frame_3)
        self.labelAutoUpdateDriversatSystemstartup.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelAutoUpdateDriversatSystemstartup.setText("")
        self.labelAutoUpdateDriversatSystemstartup.setObjectName("labelAutoUpdateDriversatSystemstartup")
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_UWP = QtWidgets.QFrame(parent=self.frame)
        self.frame_UWP.setGeometry(QtCore.QRect(10, 163, 900, 45))
        self.frame_UWP.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_UWP.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_UWP.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_UWP {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_UWP.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_UWP.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_UWP.setObjectName("frame_UWP")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_UWP)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_UWP)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setStyleSheet("background-color: transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushUWP = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushUWP.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushUWP.setMinimumSize(QtCore.QSize(91, 31))
        self.pushUWP.setMaximumSize(QtCore.QSize(91, 31))
        self.pushUWP.setBaseSize(QtCore.QSize(0, 0))
        self.pushUWP.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushUWP.setObjectName("pushUWP")
        self.labelTextUWP = QtWidgets.QLabel(parent=self.frame_4)
        self.labelTextUWP.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextUWP.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextUWP.setObjectName("labelTextUWP")
        self.labelUWP = QtWidgets.QLabel(parent=self.frame_4)
        self.labelUWP.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelUWP.setText("")
        self.labelUWP.setObjectName("labelUWP")
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_AutoUpdatingAppsStore = QtWidgets.QFrame(parent=self.frame)
        self.frame_AutoUpdatingAppsStore.setGeometry(QtCore.QRect(10, 214, 900, 45))
        self.frame_AutoUpdatingAppsStore.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_AutoUpdatingAppsStore.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_AutoUpdatingAppsStore.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_AutoUpdatingAppsStore {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_AutoUpdatingAppsStore.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AutoUpdatingAppsStore.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AutoUpdatingAppsStore.setObjectName("frame_AutoUpdatingAppsStore")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_AutoUpdatingAppsStore)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_AutoUpdatingAppsStore)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setStyleSheet("background-color: transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushAutoUpdatingAppsStore = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushAutoUpdatingAppsStore.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushAutoUpdatingAppsStore.setMinimumSize(QtCore.QSize(91, 31))
        self.pushAutoUpdatingAppsStore.setMaximumSize(QtCore.QSize(91, 31))
        self.pushAutoUpdatingAppsStore.setBaseSize(QtCore.QSize(0, 0))
        self.pushAutoUpdatingAppsStore.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushAutoUpdatingAppsStore.setObjectName("pushAutoUpdatingAppsStore")
        self.labelTextAutoUpdatingAppsStore = QtWidgets.QLabel(parent=self.frame_5)
        self.labelTextAutoUpdatingAppsStore.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextAutoUpdatingAppsStore.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextAutoUpdatingAppsStore.setObjectName("labelTextAutoUpdatingAppsStore")
        self.labelAutoUpdatingAppsStore = QtWidgets.QLabel(parent=self.frame_5)
        self.labelAutoUpdatingAppsStore.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelAutoUpdatingAppsStore.setText("")
        self.labelAutoUpdatingAppsStore.setObjectName("labelAutoUpdatingAppsStore")
        self.horizontalLayout_5.addWidget(self.frame_5)
        self.frame_Appearance = QtWidgets.QFrame(parent=self.frame)
        self.frame_Appearance.setGeometry(QtCore.QRect(10, 265, 900, 45))
        self.frame_Appearance.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_Appearance.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_Appearance.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_Appearance {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_Appearance.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Appearance.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Appearance.setObjectName("frame_Appearance")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_Appearance)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_Appearance)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setStyleSheet("background-color: transparent;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushAppearance = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushAppearance.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushAppearance.setMinimumSize(QtCore.QSize(91, 31))
        self.pushAppearance.setMaximumSize(QtCore.QSize(91, 31))
        self.pushAppearance.setBaseSize(QtCore.QSize(0, 0))
        self.pushAppearance.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushAppearance.setObjectName("pushAppearance")
        self.labelTextAppearance = QtWidgets.QLabel(parent=self.frame_6)
        self.labelTextAppearance.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextAppearance.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextAppearance.setObjectName("labelTextAppearance")
        self.labelAppearance = QtWidgets.QLabel(parent=self.frame_6)
        self.labelAppearance.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelAppearance.setText("")
        self.labelAppearance.setObjectName("labelAppearance")
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.frame_GameBar = QtWidgets.QFrame(parent=self.frame)
        self.frame_GameBar.setGeometry(QtCore.QRect(10, 316, 900, 45))
        self.frame_GameBar.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_GameBar.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_GameBar.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_GameBar {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_GameBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_GameBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_GameBar.setObjectName("frame_GameBar")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_GameBar)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_GameBar)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_7.setStyleSheet("background-color: transparent;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushGameBar = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushGameBar.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushGameBar.setMinimumSize(QtCore.QSize(91, 31))
        self.pushGameBar.setMaximumSize(QtCore.QSize(91, 31))
        self.pushGameBar.setBaseSize(QtCore.QSize(0, 0))
        self.pushGameBar.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushGameBar.setObjectName("pushGameBar")
        self.labelTextGameBar = QtWidgets.QLabel(parent=self.frame_7)
        self.labelTextGameBar.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextGameBar.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextGameBar.setObjectName("labelTextGameBar")
        self.labelGameBar = QtWidgets.QLabel(parent=self.frame_7)
        self.labelGameBar.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelGameBar.setText("")
        self.labelGameBar.setObjectName("labelGameBar")
        self.horizontalLayout_7.addWidget(self.frame_7)
        self.frame_MultyPlanOverplay = QtWidgets.QFrame(parent=self.frame)
        self.frame_MultyPlanOverplay.setGeometry(QtCore.QRect(10, 367, 900, 45))
        self.frame_MultyPlanOverplay.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_MultyPlanOverplay.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_MultyPlanOverplay.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_MultyPlanOverplay {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_MultyPlanOverplay.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_MultyPlanOverplay.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_MultyPlanOverplay.setObjectName("frame_MultyPlanOverplay")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_MultyPlanOverplay)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_MultyPlanOverplay)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_8.setStyleSheet("background-color: transparent;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushMultyPlanOverplay = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushMultyPlanOverplay.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushMultyPlanOverplay.setMinimumSize(QtCore.QSize(91, 31))
        self.pushMultyPlanOverplay.setMaximumSize(QtCore.QSize(91, 31))
        self.pushMultyPlanOverplay.setBaseSize(QtCore.QSize(0, 0))
        self.pushMultyPlanOverplay.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushMultyPlanOverplay.setObjectName("pushMultyPlanOverplay")
        self.labelTextMultyPlanOverplay = QtWidgets.QLabel(parent=self.frame_8)
        self.labelTextMultyPlanOverplay.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextMultyPlanOverplay.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextMultyPlanOverplay.setObjectName("labelTextMultyPlanOverplay")
        self.labelMultyPlanOverplay = QtWidgets.QLabel(parent=self.frame_8)
        self.labelMultyPlanOverplay.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelMultyPlanOverplay.setText("")
        self.labelMultyPlanOverplay.setObjectName("labelMultyPlanOverplay")
        self.horizontalLayout_8.addWidget(self.frame_8)
        self.frame_WindowsFirewall = QtWidgets.QFrame(parent=self.frame)
        self.frame_WindowsFirewall.setGeometry(QtCore.QRect(10, 418, 900, 45))
        self.frame_WindowsFirewall.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_WindowsFirewall.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_WindowsFirewall.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_WindowsFirewall {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_WindowsFirewall.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_WindowsFirewall.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_WindowsFirewall.setObjectName("frame_WindowsFirewall")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_WindowsFirewall)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_WindowsFirewall)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_9.setStyleSheet("background-color: transparent;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushWindowsFirewall = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushWindowsFirewall.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushWindowsFirewall.setMinimumSize(QtCore.QSize(91, 31))
        self.pushWindowsFirewall.setMaximumSize(QtCore.QSize(91, 31))
        self.pushWindowsFirewall.setBaseSize(QtCore.QSize(0, 0))
        self.pushWindowsFirewall.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushWindowsFirewall.setObjectName("pushWindowsFirewall")
        self.labelTextWindowsFirewall = QtWidgets.QLabel(parent=self.frame_9)
        self.labelTextWindowsFirewall.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextWindowsFirewall.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextWindowsFirewall.setObjectName("labelTextWindowsFirewall")
        self.labelWindowsFirewall = QtWidgets.QLabel(parent=self.frame_9)
        self.labelWindowsFirewall.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelWindowsFirewall.setText("")
        self.labelWindowsFirewall.setObjectName("labelWindowsFirewall")
        self.horizontalLayout_9.addWidget(self.frame_9)
        self.frame_UAC = QtWidgets.QFrame(parent=self.frame)
        self.frame_UAC.setGeometry(QtCore.QRect(10, 469, 900, 45))
        self.frame_UAC.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_UAC.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_UAC.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_UAC {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_UAC.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_UAC.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_UAC.setObjectName("frame_UAC")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_UAC)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_UAC)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_10.setStyleSheet("background-color: transparent;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.pushWindowsUAC = QtWidgets.QPushButton(parent=self.frame_10)
        self.pushWindowsUAC.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushWindowsUAC.setMinimumSize(QtCore.QSize(91, 31))
        self.pushWindowsUAC.setMaximumSize(QtCore.QSize(91, 31))
        self.pushWindowsUAC.setBaseSize(QtCore.QSize(0, 0))
        self.pushWindowsUAC.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushWindowsUAC.setObjectName("pushWindowsUAC")
        self.labelTextUAC = QtWidgets.QLabel(parent=self.frame_10)
        self.labelTextUAC.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextUAC.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextUAC.setObjectName("labelTextUAC")
        self.labelWindowsUAC = QtWidgets.QLabel(parent=self.frame_10)
        self.labelWindowsUAC.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelWindowsUAC.setText("")
        self.labelWindowsUAC.setObjectName("labelWindowsUAC")
        self.horizontalLayout_10.addWidget(self.frame_10)
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(370, 10, 201, 21))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \'Arial\'; /* Замените на нужное семейство шрифтов */\n"
"    font-size: 20px; /* Замените на нужный размер шрифта */\n"
"    color: white; /* Замените на нужный цвет текста */\n"
"    font-weight: bold; /* Для жирного текста */\n"
"}")
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(BaseSettings)
        QtCore.QMetaObject.connectSlotsByName(BaseSettings)

    def retranslateUi(self, BaseSettings):
        _translate = QtCore.QCoreApplication.translate
        BaseSettings.setWindowTitle(_translate("BaseSettings", "Form"))
        self.pushMouseAcceleration.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextMouseAcceleration.setText(_translate("BaseSettings", "Акселирация мыши"))
        self.pushProtectionNotifications.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextProtectionNotifications.setText(_translate("BaseSettings", "Уведомления защиты"))
        self.pushAutoUpdateDriversatSystemstartup.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextAutoUpdateDriversatSystemstartup.setText(_translate("BaseSettings", "Автообновление драйверов при запуске системы"))
        self.pushUWP.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextUWP.setText(_translate("BaseSettings", "Работа UWP приложений в фоне"))
        self.pushAutoUpdatingAppsStore.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextAutoUpdatingAppsStore.setText(_translate("BaseSettings", "Автообновление приложений в магазине"))
        self.pushAppearance.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextAppearance.setText(_translate("BaseSettings", "Внешний вид"))
        self.pushGameBar.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextGameBar.setText(_translate("BaseSettings", "GameBar"))
        self.pushMultyPlanOverplay.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextMultyPlanOverplay.setText(_translate("BaseSettings", "Multy Plan Overplay"))
        self.pushWindowsFirewall.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextWindowsFirewall.setText(_translate("BaseSettings", "Брандмауэр Windows"))
        self.pushWindowsUAC.setText(_translate("BaseSettings", "Очистка"))
        self.labelTextUAC.setText(_translate("BaseSettings", "Контроль учетных записей (UAC)"))
        self.label.setText(_translate("BaseSettings", "Базовые настройки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BaseSettings = QtWidgets.QWidget()
    ui = Ui_BaseSettings()
    ui.setupUi(BaseSettings)
    BaseSettings.show()
    sys.exit(app.exec())
