# Form implementation generated from reading ui file '.\EnergyPower.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Energy(object):
    def setupUi(self, Energy):
        Energy.setObjectName("Energy")
        Energy.resize(1114, 731)
        Energy.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(parent=Energy)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1015, 602))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(820, 20, 120, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 961, 581))
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
"*{\n"
"margin:0\n"
"\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #161A1E;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #34373b;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:#161A1E;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #161A1E;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 945, 700))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 700))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(10, 20, 961, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_Energy = QtWidgets.QFrame(parent=self.frame)
        self.frame_Energy.setGeometry(QtCore.QRect(0, 10, 831, 45))
        self.frame_Energy.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_Energy.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_Energy {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_Energy.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Energy.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Energy.setObjectName("frame_Energy")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_Energy)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_Energy_Preset = QtWidgets.QFrame(parent=self.frame_Energy)
        self.frame_Energy_Preset.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_Energy_Preset.setStyleSheet("background-color: transparent;")
        self.frame_Energy_Preset.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Energy_Preset.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Energy_Preset.setObjectName("frame_Energy_Preset")
        self.labelEnergy_Preset = QtWidgets.QLabel(parent=self.frame_Energy_Preset)
        self.labelEnergy_Preset.setGeometry(QtCore.QRect(760, 10, 70, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelEnergy_Preset.sizePolicy().hasHeightForWidth())
        self.labelEnergy_Preset.setSizePolicy(sizePolicy)
        self.labelEnergy_Preset.setMinimumSize(QtCore.QSize(70, 30))
        self.labelEnergy_Preset.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelEnergy_Preset.setText("")
        self.labelEnergy_Preset.setObjectName("labelEnergy_Preset")
        self.pushEnergy_Preset = QtWidgets.QPushButton(parent=self.frame_Energy_Preset)
        self.pushEnergy_Preset.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushEnergy_Preset.setMinimumSize(QtCore.QSize(91, 31))
        self.pushEnergy_Preset.setMaximumSize(QtCore.QSize(91, 31))
        self.pushEnergy_Preset.setBaseSize(QtCore.QSize(0, 0))
        self.pushEnergy_Preset.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushEnergy_Preset.setObjectName("pushEnergy_Preset")
        self.labelTextEnergy_Preset = QtWidgets.QLabel(parent=self.frame_Energy_Preset)
        self.labelTextEnergy_Preset.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.labelTextEnergy_Preset.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextEnergy_Preset.setObjectName("labelTextEnergy_Preset")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_Energy_Preset)
        self.stackedWidget.setGeometry(QtCore.QRect(410, 10, 120, 31))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.frame_Energy_Preset)
        self.frame_Pow = QtWidgets.QFrame(parent=self.frame)
        self.frame_Pow.setGeometry(QtCore.QRect(0, 70, 831, 50))
        self.frame_Pow.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_Pow.setStyleSheet("#frame_Pow {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_Pow.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Pow.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Pow.setObjectName("frame_Pow")
        self.pushPow = QtWidgets.QPushButton(parent=self.frame_Pow)
        self.pushPow.setGeometry(QtCore.QRect(730, 10, 91, 35))
        self.pushPow.setMinimumSize(QtCore.QSize(91, 31))
        self.pushPow.setMaximumSize(QtCore.QSize(91, 31))
        self.pushPow.setBaseSize(QtCore.QSize(0, 0))
        self.pushPow.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushPow.setText("")
        self.pushPow.setObjectName("pushPow")
        self.labelTextPow = QtWidgets.QLabel(parent=self.frame_Pow)
        self.labelTextPow.setGeometry(QtCore.QRect(30, 10, 231, 21))
        self.labelTextPow.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    background-color: #161A1E;\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextPow.setObjectName("labelTextPow")
        self.frame_Hibernation = QtWidgets.QFrame(parent=self.frame)
        self.frame_Hibernation.setGeometry(QtCore.QRect(0, 150, 831, 50))
        self.frame_Hibernation.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_Hibernation.setStyleSheet("#frame_Hibernation {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_Hibernation.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Hibernation.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Hibernation.setObjectName("frame_Hibernation")
        self.pushHibernation = QtWidgets.QPushButton(parent=self.frame_Hibernation)
        self.pushHibernation.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushHibernation.setMinimumSize(QtCore.QSize(91, 31))
        self.pushHibernation.setMaximumSize(QtCore.QSize(91, 31))
        self.pushHibernation.setBaseSize(QtCore.QSize(0, 0))
        self.pushHibernation.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushHibernation.setText("")
        self.pushHibernation.setObjectName("pushHibernation")
        self.labelTextHibernation = QtWidgets.QLabel(parent=self.frame_Hibernation)
        self.labelTextHibernation.setGeometry(QtCore.QRect(30, 10, 231, 21))
        self.labelTextHibernation.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    background-color: #161A1E;\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextHibernation.setObjectName("labelTextHibernation")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Energy)
        QtCore.QMetaObject.connectSlotsByName(Energy)

    def retranslateUi(self, Energy):
        _translate = QtCore.QCoreApplication.translate
        Energy.setWindowTitle(_translate("Energy", "Form"))
        self.pushEnergy_Preset.setText(_translate("Energy", "Выбрать"))
        self.labelTextEnergy_Preset.setText(_translate("Energy", "Электропитание"))
        self.labelTextPow.setText(_translate("Energy", "Возможность импорта .pow файлов"))
        self.labelTextHibernation.setText(_translate("Energy", "Гибернация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Energy = QtWidgets.QWidget()
    ui = Ui_Energy()
    ui.setupUi(Energy)
    Energy.show()
    sys.exit(app.exec())
