# Form implementation generated from reading ui file '.\Task.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Task(object):
    def setupUi(self, Task):
        Task.setObjectName("Task")
        Task.resize(1114, 576)
        Task.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(parent=Task)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1015, 602))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(820, 20, 120, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 961, 581))
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
"*{\n"
"margin:0\n"
"\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #161A1E;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #34373b;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:#161A1E;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #161A1E;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 945, 670))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 670))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(10, 10, 920, 626))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_TasksForAnalysis = QtWidgets.QFrame(parent=self.frame)
        self.frame_TasksForAnalysis.setGeometry(QtCore.QRect(10, 10, 900, 45))
        self.frame_TasksForAnalysis.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_TasksForAnalysis.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_TasksForAnalysis.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_TasksForAnalysis {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_TasksForAnalysis.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_TasksForAnalysis.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_TasksForAnalysis.setObjectName("frame_TasksForAnalysis")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_TasksForAnalysis)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_1 = QtWidgets.QFrame(parent=self.frame_TasksForAnalysis)
        self.frame_1.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_1.setStyleSheet("background-color: transparent;")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_1.setObjectName("frame_1")
        self.pushTasksForAnalysis = QtWidgets.QPushButton(parent=self.frame_1)
        self.pushTasksForAnalysis.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushTasksForAnalysis.setMinimumSize(QtCore.QSize(91, 31))
        self.pushTasksForAnalysis.setMaximumSize(QtCore.QSize(91, 31))
        self.pushTasksForAnalysis.setBaseSize(QtCore.QSize(0, 0))
        self.pushTasksForAnalysis.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushTasksForAnalysis.setObjectName("pushTasksForAnalysis")
        self.labelTextTasksForAnalysis = QtWidgets.QLabel(parent=self.frame_1)
        self.labelTextTasksForAnalysis.setGeometry(QtCore.QRect(30, 10, 151, 21))
        self.labelTextTasksForAnalysis.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextTasksForAnalysis.setObjectName("labelTextTasksForAnalysis")
        self.labelTasksForAnalysis = QtWidgets.QLabel(parent=self.frame_1)
        self.labelTasksForAnalysis.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelTasksForAnalysis.setText("")
        self.labelTasksForAnalysis.setObjectName("labelTasksForAnalysis")
        self.horizontalLayout.addWidget(self.frame_1)
        self.frame_DiagnosticTasks = QtWidgets.QFrame(parent=self.frame)
        self.frame_DiagnosticTasks.setGeometry(QtCore.QRect(10, 61, 900, 45))
        self.frame_DiagnosticTasks.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_DiagnosticTasks.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_DiagnosticTasks.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_DiagnosticTasks {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_DiagnosticTasks.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_DiagnosticTasks.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_DiagnosticTasks.setObjectName("frame_DiagnosticTasks")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_DiagnosticTasks)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_DiagnosticTasks)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setStyleSheet("background-color: transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushDiagnosticTasks = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushDiagnosticTasks.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushDiagnosticTasks.setMinimumSize(QtCore.QSize(91, 31))
        self.pushDiagnosticTasks.setMaximumSize(QtCore.QSize(91, 31))
        self.pushDiagnosticTasks.setBaseSize(QtCore.QSize(0, 0))
        self.pushDiagnosticTasks.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushDiagnosticTasks.setObjectName("pushDiagnosticTasks")
        self.labelTextDiagnosticTasks = QtWidgets.QLabel(parent=self.frame_2)
        self.labelTextDiagnosticTasks.setGeometry(QtCore.QRect(30, 10, 201, 21))
        self.labelTextDiagnosticTasks.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextDiagnosticTasks.setObjectName("labelTextDiagnosticTasks")
        self.labelDiagnosticTasks = QtWidgets.QLabel(parent=self.frame_2)
        self.labelDiagnosticTasks.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelDiagnosticTasks.setText("")
        self.labelDiagnosticTasks.setObjectName("labelDiagnosticTasks")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_NetPrecompilation = QtWidgets.QFrame(parent=self.frame)
        self.frame_NetPrecompilation.setGeometry(QtCore.QRect(10, 112, 900, 45))
        self.frame_NetPrecompilation.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_NetPrecompilation.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_NetPrecompilation.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_NetPrecompilation {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_NetPrecompilation.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_NetPrecompilation.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_NetPrecompilation.setObjectName("frame_NetPrecompilation")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_NetPrecompilation)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_NetPrecompilation)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setStyleSheet("background-color: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushNetPrecompilation = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushNetPrecompilation.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushNetPrecompilation.setMinimumSize(QtCore.QSize(91, 31))
        self.pushNetPrecompilation.setMaximumSize(QtCore.QSize(91, 31))
        self.pushNetPrecompilation.setBaseSize(QtCore.QSize(0, 0))
        self.pushNetPrecompilation.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushNetPrecompilation.setObjectName("pushNetPrecompilation")
        self.labelTextNetPrecompilation = QtWidgets.QLabel(parent=self.frame_3)
        self.labelTextNetPrecompilation.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextNetPrecompilation.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextNetPrecompilation.setObjectName("labelTextNetPrecompilation")
        self.labelNetPrecompilation = QtWidgets.QLabel(parent=self.frame_3)
        self.labelNetPrecompilation.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelNetPrecompilation.setText("")
        self.labelNetPrecompilation.setObjectName("labelNetPrecompilation")
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_AutoProxyDetection = QtWidgets.QFrame(parent=self.frame)
        self.frame_AutoProxyDetection.setGeometry(QtCore.QRect(10, 163, 900, 45))
        self.frame_AutoProxyDetection.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_AutoProxyDetection.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_AutoProxyDetection.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_AutoProxyDetection {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_AutoProxyDetection.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AutoProxyDetection.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AutoProxyDetection.setObjectName("frame_AutoProxyDetection")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_AutoProxyDetection)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_AutoProxyDetection)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setStyleSheet("background-color: transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushAutoProxyDetection = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushAutoProxyDetection.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushAutoProxyDetection.setMinimumSize(QtCore.QSize(91, 31))
        self.pushAutoProxyDetection.setMaximumSize(QtCore.QSize(91, 31))
        self.pushAutoProxyDetection.setBaseSize(QtCore.QSize(0, 0))
        self.pushAutoProxyDetection.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushAutoProxyDetection.setObjectName("pushAutoProxyDetection")
        self.labelTextAutoProxyDetection = QtWidgets.QLabel(parent=self.frame_4)
        self.labelTextAutoProxyDetection.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextAutoProxyDetection.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextAutoProxyDetection.setObjectName("labelTextAutoProxyDetection")
        self.labelAutoProxyDetection = QtWidgets.QLabel(parent=self.frame_4)
        self.labelAutoProxyDetection.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelAutoProxyDetection.setText("")
        self.labelAutoProxyDetection.setObjectName("labelAutoProxyDetection")
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_InstallingAndRemovingLanguages = QtWidgets.QFrame(parent=self.frame)
        self.frame_InstallingAndRemovingLanguages.setGeometry(QtCore.QRect(10, 214, 900, 45))
        self.frame_InstallingAndRemovingLanguages.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_InstallingAndRemovingLanguages.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_InstallingAndRemovingLanguages.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_InstallingAndRemovingLanguages {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_InstallingAndRemovingLanguages.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_InstallingAndRemovingLanguages.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_InstallingAndRemovingLanguages.setObjectName("frame_InstallingAndRemovingLanguages")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_InstallingAndRemovingLanguages)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_InstallingAndRemovingLanguages)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setStyleSheet("background-color: transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushInstallingAndRemovingLanguages = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushInstallingAndRemovingLanguages.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushInstallingAndRemovingLanguages.setMinimumSize(QtCore.QSize(91, 31))
        self.pushInstallingAndRemovingLanguages.setMaximumSize(QtCore.QSize(91, 31))
        self.pushInstallingAndRemovingLanguages.setBaseSize(QtCore.QSize(0, 0))
        self.pushInstallingAndRemovingLanguages.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushInstallingAndRemovingLanguages.setObjectName("pushInstallingAndRemovingLanguages")
        self.labelTextInstallingAndRemovingLanguages = QtWidgets.QLabel(parent=self.frame_5)
        self.labelTextInstallingAndRemovingLanguages.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextInstallingAndRemovingLanguages.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextInstallingAndRemovingLanguages.setObjectName("labelTextInstallingAndRemovingLanguages")
        self.labelInstallingAndRemovingLanguages = QtWidgets.QLabel(parent=self.frame_5)
        self.labelInstallingAndRemovingLanguages.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelInstallingAndRemovingLanguages.setText("")
        self.labelInstallingAndRemovingLanguages.setObjectName("labelInstallingAndRemovingLanguages")
        self.horizontalLayout_5.addWidget(self.frame_5)
        self.frame_AutoPerformanceCheck = QtWidgets.QFrame(parent=self.frame)
        self.frame_AutoPerformanceCheck.setGeometry(QtCore.QRect(10, 265, 900, 45))
        self.frame_AutoPerformanceCheck.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_AutoPerformanceCheck.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_AutoPerformanceCheck.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_AutoPerformanceCheck {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_AutoPerformanceCheck.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AutoPerformanceCheck.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AutoPerformanceCheck.setObjectName("frame_AutoPerformanceCheck")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_AutoPerformanceCheck)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_AutoPerformanceCheck)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setStyleSheet("background-color: transparent;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushAutoPerformanceCheck = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushAutoPerformanceCheck.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushAutoPerformanceCheck.setMinimumSize(QtCore.QSize(91, 31))
        self.pushAutoPerformanceCheck.setMaximumSize(QtCore.QSize(91, 31))
        self.pushAutoPerformanceCheck.setBaseSize(QtCore.QSize(0, 0))
        self.pushAutoPerformanceCheck.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushAutoPerformanceCheck.setObjectName("pushAutoPerformanceCheck")
        self.labelTextAutoPerformanceCheck = QtWidgets.QLabel(parent=self.frame_6)
        self.labelTextAutoPerformanceCheck.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextAutoPerformanceCheck.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextAutoPerformanceCheck.setObjectName("labelTextAutoPerformanceCheck")
        self.labelAutoPerformanceCheck = QtWidgets.QLabel(parent=self.frame_6)
        self.labelAutoPerformanceCheck.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelAutoPerformanceCheck.setText("")
        self.labelAutoPerformanceCheck.setObjectName("labelAutoPerformanceCheck")
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.frame_MapsLocation = QtWidgets.QFrame(parent=self.frame)
        self.frame_MapsLocation.setGeometry(QtCore.QRect(10, 316, 900, 45))
        self.frame_MapsLocation.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_MapsLocation.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_MapsLocation.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_MapsLocation {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_MapsLocation.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_MapsLocation.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_MapsLocation.setObjectName("frame_MapsLocation")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_MapsLocation)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_MapsLocation)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_7.setStyleSheet("background-color: transparent;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushMapsLocation = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushMapsLocation.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushMapsLocation.setMinimumSize(QtCore.QSize(91, 31))
        self.pushMapsLocation.setMaximumSize(QtCore.QSize(91, 31))
        self.pushMapsLocation.setBaseSize(QtCore.QSize(0, 0))
        self.pushMapsLocation.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushMapsLocation.setObjectName("pushMapsLocation")
        self.labelTextMapsLocation = QtWidgets.QLabel(parent=self.frame_7)
        self.labelTextMapsLocation.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextMapsLocation.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextMapsLocation.setObjectName("labelTextMapsLocation")
        self.labelMapsLocation = QtWidgets.QLabel(parent=self.frame_7)
        self.labelMapsLocation.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelMapsLocation.setText("")
        self.labelMapsLocation.setObjectName("labelMapsLocation")
        self.horizontalLayout_7.addWidget(self.frame_7)
        self.frame_RemoteControl = QtWidgets.QFrame(parent=self.frame)
        self.frame_RemoteControl.setGeometry(QtCore.QRect(10, 367, 900, 45))
        self.frame_RemoteControl.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_RemoteControl.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_RemoteControl.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_RemoteControl {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_RemoteControl.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_RemoteControl.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_RemoteControl.setObjectName("frame_RemoteControl")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_RemoteControl)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_RemoteControl)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_8.setStyleSheet("background-color: transparent;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushRemoteControl = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushRemoteControl.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushRemoteControl.setMinimumSize(QtCore.QSize(91, 31))
        self.pushRemoteControl.setMaximumSize(QtCore.QSize(91, 31))
        self.pushRemoteControl.setBaseSize(QtCore.QSize(0, 0))
        self.pushRemoteControl.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushRemoteControl.setObjectName("pushRemoteControl")
        self.labelTextRemoteControl = QtWidgets.QLabel(parent=self.frame_8)
        self.labelTextRemoteControl.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextRemoteControl.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextRemoteControl.setObjectName("labelTextRemoteControl")
        self.labelRemoteControl = QtWidgets.QLabel(parent=self.frame_8)
        self.labelRemoteControl.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelRemoteControl.setText("")
        self.labelRemoteControl.setObjectName("labelRemoteControl")
        self.horizontalLayout_8.addWidget(self.frame_8)
        self.frame_MicrosoftSync = QtWidgets.QFrame(parent=self.frame)
        self.frame_MicrosoftSync.setGeometry(QtCore.QRect(10, 418, 900, 45))
        self.frame_MicrosoftSync.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_MicrosoftSync.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_MicrosoftSync.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_MicrosoftSync {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_MicrosoftSync.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_MicrosoftSync.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_MicrosoftSync.setObjectName("frame_MicrosoftSync")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_MicrosoftSync)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_MicrosoftSync)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_9.setStyleSheet("background-color: transparent;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushMicrosoftSync = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushMicrosoftSync.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushMicrosoftSync.setMinimumSize(QtCore.QSize(91, 31))
        self.pushMicrosoftSync.setMaximumSize(QtCore.QSize(91, 31))
        self.pushMicrosoftSync.setBaseSize(QtCore.QSize(0, 0))
        self.pushMicrosoftSync.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushMicrosoftSync.setObjectName("pushMicrosoftSync")
        self.labelTextMicrosoftSync = QtWidgets.QLabel(parent=self.frame_9)
        self.labelTextMicrosoftSync.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextMicrosoftSync.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextMicrosoftSync.setObjectName("labelTextMicrosoftSync")
        self.labelMicrosoftSync = QtWidgets.QLabel(parent=self.frame_9)
        self.labelMicrosoftSync.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelMicrosoftSync.setText("")
        self.labelMicrosoftSync.setObjectName("labelMicrosoftSync")
        self.horizontalLayout_9.addWidget(self.frame_9)
        self.frame_CleaningTasks = QtWidgets.QFrame(parent=self.frame)
        self.frame_CleaningTasks.setGeometry(QtCore.QRect(10, 469, 900, 45))
        self.frame_CleaningTasks.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_CleaningTasks.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_CleaningTasks.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_CleaningTasks {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_CleaningTasks.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_CleaningTasks.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_CleaningTasks.setObjectName("frame_CleaningTasks")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_CleaningTasks)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_CleaningTasks)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_10.setStyleSheet("background-color: transparent;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.pushCleaningTasks = QtWidgets.QPushButton(parent=self.frame_10)
        self.pushCleaningTasks.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushCleaningTasks.setMinimumSize(QtCore.QSize(91, 31))
        self.pushCleaningTasks.setMaximumSize(QtCore.QSize(91, 31))
        self.pushCleaningTasks.setBaseSize(QtCore.QSize(0, 0))
        self.pushCleaningTasks.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushCleaningTasks.setObjectName("pushCleaningTasks")
        self.labelTextCleaningTasks = QtWidgets.QLabel(parent=self.frame_10)
        self.labelTextCleaningTasks.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextCleaningTasks.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextCleaningTasks.setObjectName("labelTextCleaningTasks")
        self.labelCleaningTasks = QtWidgets.QLabel(parent=self.frame_10)
        self.labelCleaningTasks.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelCleaningTasks.setText("")
        self.labelCleaningTasks.setObjectName("labelCleaningTasks")
        self.horizontalLayout_10.addWidget(self.frame_10)
        self.frame_MicrosoftStore = QtWidgets.QFrame(parent=self.frame)
        self.frame_MicrosoftStore.setGeometry(QtCore.QRect(10, 520, 900, 45))
        self.frame_MicrosoftStore.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_MicrosoftStore.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_MicrosoftStore.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_MicrosoftStore {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_MicrosoftStore.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_MicrosoftStore.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_MicrosoftStore.setObjectName("frame_MicrosoftStore")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_MicrosoftStore)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_MicrosoftStore)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_11.setStyleSheet("background-color: transparent;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.pushMicrosoftStore = QtWidgets.QPushButton(parent=self.frame_11)
        self.pushMicrosoftStore.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushMicrosoftStore.setMinimumSize(QtCore.QSize(91, 31))
        self.pushMicrosoftStore.setMaximumSize(QtCore.QSize(91, 31))
        self.pushMicrosoftStore.setBaseSize(QtCore.QSize(0, 0))
        self.pushMicrosoftStore.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushMicrosoftStore.setObjectName("pushMicrosoftStore")
        self.labelTextMicrosoftStore = QtWidgets.QLabel(parent=self.frame_11)
        self.labelTextMicrosoftStore.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextMicrosoftStore.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextMicrosoftStore.setObjectName("labelTextMicrosoftStore")
        self.labelMicrosoftStore = QtWidgets.QLabel(parent=self.frame_11)
        self.labelMicrosoftStore.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelMicrosoftStore.setText("")
        self.labelMicrosoftStore.setObjectName("labelMicrosoftStore")
        self.horizontalLayout_11.addWidget(self.frame_11)
        self.frame_XBOX = QtWidgets.QFrame(parent=self.frame)
        self.frame_XBOX.setGeometry(QtCore.QRect(10, 571, 900, 45))
        self.frame_XBOX.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_XBOX.setMaximumSize(QtCore.QSize(900, 45))
        self.frame_XBOX.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_XBOX {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_XBOX.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_XBOX.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_XBOX.setObjectName("frame_XBOX")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_XBOX)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_XBOX)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_13.setStyleSheet("background-color: transparent;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.pushWindowsXBOX = QtWidgets.QPushButton(parent=self.frame_13)
        self.pushWindowsXBOX.setGeometry(QtCore.QRect(790, 0, 91, 31))
        self.pushWindowsXBOX.setMinimumSize(QtCore.QSize(91, 31))
        self.pushWindowsXBOX.setMaximumSize(QtCore.QSize(91, 31))
        self.pushWindowsXBOX.setBaseSize(QtCore.QSize(0, 0))
        self.pushWindowsXBOX.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushWindowsXBOX.setObjectName("pushWindowsXBOX")
        self.labelTextXBOX = QtWidgets.QLabel(parent=self.frame_13)
        self.labelTextXBOX.setGeometry(QtCore.QRect(30, 10, 341, 21))
        self.labelTextXBOX.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextXBOX.setObjectName("labelTextXBOX")
        self.labelWindowsXBOX = QtWidgets.QLabel(parent=self.frame_13)
        self.labelWindowsXBOX.setGeometry(QtCore.QRect(616, 10, 101, 20))
        self.labelWindowsXBOX.setText("")
        self.labelWindowsXBOX.setObjectName("labelWindowsXBOX")
        self.horizontalLayout_13.addWidget(self.frame_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Task)
        QtCore.QMetaObject.connectSlotsByName(Task)

    def retranslateUi(self, Task):
        _translate = QtCore.QCoreApplication.translate
        Task.setWindowTitle(_translate("Task", "Form"))
        self.pushTasksForAnalysis.setText(_translate("Task", "Очистка"))
        self.labelTextTasksForAnalysis.setText(_translate("Task", "Задачи для анализа"))
        self.pushDiagnosticTasks.setText(_translate("Task", "Очистка"))
        self.labelTextDiagnosticTasks.setText(_translate("Task", "Задачи для диагностики"))
        self.pushNetPrecompilation.setText(_translate("Task", "Очистка"))
        self.labelTextNetPrecompilation.setText(_translate("Task", "Предворительная компиляция .Net"))
        self.pushAutoProxyDetection.setText(_translate("Task", "Очистка"))
        self.labelTextAutoProxyDetection.setText(_translate("Task", "Авто-определение прокси "))
        self.pushInstallingAndRemovingLanguages.setText(_translate("Task", "Очистка"))
        self.labelTextInstallingAndRemovingLanguages.setText(_translate("Task", "Установка и удаление языков"))
        self.pushAutoPerformanceCheck.setText(_translate("Task", "Очистка"))
        self.labelTextAutoPerformanceCheck.setText(_translate("Task", "Авто-проверка производительности"))
        self.pushMapsLocation.setText(_translate("Task", "Очистка"))
        self.labelTextMapsLocation.setText(_translate("Task", "Карты и локация"))
        self.pushRemoteControl.setText(_translate("Task", "Очистка"))
        self.labelTextRemoteControl.setText(_translate("Task", "Удаленное управление"))
        self.pushMicrosoftSync.setText(_translate("Task", "Очистка"))
        self.labelTextMicrosoftSync.setText(_translate("Task", "Синхронизация Microsoft"))
        self.pushCleaningTasks.setText(_translate("Task", "Очистка"))
        self.labelTextCleaningTasks.setText(_translate("Task", "Задачи очистки"))
        self.pushMicrosoftStore.setText(_translate("Task", "Очистка"))
        self.labelTextMicrosoftStore.setText(_translate("Task", "Microsoft Store"))
        self.pushWindowsXBOX.setText(_translate("Task", "Очистка"))
        self.labelTextXBOX.setText(_translate("Task", "Xbox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Task = QtWidgets.QWidget()
    ui = Ui_Task()
    ui.setupUi(Task)
    Task.show()
    sys.exit(app.exec())
