# Form implementation generated from reading ui file '.\Twics.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Twics(object):
    def setupUi(self, Twics):
        Twics.setObjectName("Twics")
        Twics.resize(1114, 731)
        Twics.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(parent=Twics)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1015, 602))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(820, 20, 120, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 961, 581))
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
"*{\n"
"margin:0\n"
"\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #161A1E;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #34373b;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:#161A1E;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #161A1E;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 959, 579))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(10, 20, 931, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_SystemResponsiveness = QtWidgets.QFrame(parent=self.frame)
        self.frame_SystemResponsiveness.setGeometry(QtCore.QRect(10, 10, 921, 45))
        self.frame_SystemResponsiveness.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_SystemResponsiveness.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_SystemResponsiveness {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_SystemResponsiveness.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SystemResponsiveness.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SystemResponsiveness.setObjectName("frame_SystemResponsiveness")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_SystemResponsiveness)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_SystemResponsiveness_2 = QtWidgets.QFrame(parent=self.frame_SystemResponsiveness)
        self.frame_SystemResponsiveness_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_SystemResponsiveness_2.setStyleSheet("background-color: transparent;")
        self.frame_SystemResponsiveness_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SystemResponsiveness_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SystemResponsiveness_2.setObjectName("frame_SystemResponsiveness_2")
        self.labelSystemResponsiveness = QtWidgets.QLabel(parent=self.frame_SystemResponsiveness_2)
        self.labelSystemResponsiveness.setGeometry(QtCore.QRect(580, 10, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelSystemResponsiveness.sizePolicy().hasHeightForWidth())
        self.labelSystemResponsiveness.setSizePolicy(sizePolicy)
        self.labelSystemResponsiveness.setMinimumSize(QtCore.QSize(70, 30))
        self.labelSystemResponsiveness.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelSystemResponsiveness.setText("")
        self.labelSystemResponsiveness.setObjectName("labelSystemResponsiveness")
        self.pushSystemResponsiveness = QtWidgets.QPushButton(parent=self.frame_SystemResponsiveness_2)
        self.pushSystemResponsiveness.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushSystemResponsiveness.setMinimumSize(QtCore.QSize(91, 31))
        self.pushSystemResponsiveness.setMaximumSize(QtCore.QSize(91, 31))
        self.pushSystemResponsiveness.setBaseSize(QtCore.QSize(0, 0))
        self.pushSystemResponsiveness.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushSystemResponsiveness.setObjectName("pushSystemResponsiveness")
        self.labelTextSystemResponsiveness = QtWidgets.QLabel(parent=self.frame_SystemResponsiveness_2)
        self.labelTextSystemResponsiveness.setGeometry(QtCore.QRect(30, 10, 151, 21))
        self.labelTextSystemResponsiveness.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextSystemResponsiveness.setObjectName("labelTextSystemResponsiveness")
        self.horizontalLayout.addWidget(self.frame_SystemResponsiveness_2)
        self.frame_Win32PrioritySeparation = QtWidgets.QFrame(parent=self.frame)
        self.frame_Win32PrioritySeparation.setGeometry(QtCore.QRect(10, 61, 921, 45))
        self.frame_Win32PrioritySeparation.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_Win32PrioritySeparation.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_Win32PrioritySeparation {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_Win32PrioritySeparation.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Win32PrioritySeparation.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Win32PrioritySeparation.setObjectName("frame_Win32PrioritySeparation")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Win32PrioritySeparation)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_Energy_Preset_2 = QtWidgets.QFrame(parent=self.frame_Win32PrioritySeparation)
        self.frame_Energy_Preset_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_Energy_Preset_2.setStyleSheet("background-color: transparent;")
        self.frame_Energy_Preset_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Energy_Preset_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Energy_Preset_2.setObjectName("frame_Energy_Preset_2")
        self.labelWin32PrioritySeparation = QtWidgets.QLabel(parent=self.frame_Energy_Preset_2)
        self.labelWin32PrioritySeparation.setGeometry(QtCore.QRect(580, 10, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelWin32PrioritySeparation.sizePolicy().hasHeightForWidth())
        self.labelWin32PrioritySeparation.setSizePolicy(sizePolicy)
        self.labelWin32PrioritySeparation.setMinimumSize(QtCore.QSize(70, 30))
        self.labelWin32PrioritySeparation.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelWin32PrioritySeparation.setText("")
        self.labelWin32PrioritySeparation.setObjectName("labelWin32PrioritySeparation")
        self.pushWin32PrioritySeparation = QtWidgets.QPushButton(parent=self.frame_Energy_Preset_2)
        self.pushWin32PrioritySeparation.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushWin32PrioritySeparation.setMinimumSize(QtCore.QSize(91, 31))
        self.pushWin32PrioritySeparation.setMaximumSize(QtCore.QSize(91, 31))
        self.pushWin32PrioritySeparation.setBaseSize(QtCore.QSize(0, 0))
        self.pushWin32PrioritySeparation.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushWin32PrioritySeparation.setObjectName("pushWin32PrioritySeparation")
        self.labelTextWin32PrioritySeparation = QtWidgets.QLabel(parent=self.frame_Energy_Preset_2)
        self.labelTextWin32PrioritySeparation.setGeometry(QtCore.QRect(30, 10, 161, 21))
        self.labelTextWin32PrioritySeparation.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextWin32PrioritySeparation.setObjectName("labelTextWin32PrioritySeparation")
        self.horizontalLayout_2.addWidget(self.frame_Energy_Preset_2)
        self.frame_SpectreMeltdown = QtWidgets.QFrame(parent=self.frame)
        self.frame_SpectreMeltdown.setGeometry(QtCore.QRect(10, 112, 921, 45))
        self.frame_SpectreMeltdown.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_SpectreMeltdown.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_SpectreMeltdown {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_SpectreMeltdown.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SpectreMeltdown.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SpectreMeltdown.setObjectName("frame_SpectreMeltdown")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_SpectreMeltdown)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_SpectreMeltdown_2 = QtWidgets.QFrame(parent=self.frame_SpectreMeltdown)
        self.frame_SpectreMeltdown_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_SpectreMeltdown_2.setStyleSheet("background-color: transparent;")
        self.frame_SpectreMeltdown_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SpectreMeltdown_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SpectreMeltdown_2.setObjectName("frame_SpectreMeltdown_2")
        self.labelSpectreMeltdown = QtWidgets.QLabel(parent=self.frame_SpectreMeltdown_2)
        self.labelSpectreMeltdown.setGeometry(QtCore.QRect(579, 10, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelSpectreMeltdown.sizePolicy().hasHeightForWidth())
        self.labelSpectreMeltdown.setSizePolicy(sizePolicy)
        self.labelSpectreMeltdown.setMinimumSize(QtCore.QSize(70, 30))
        self.labelSpectreMeltdown.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelSpectreMeltdown.setText("")
        self.labelSpectreMeltdown.setObjectName("labelSpectreMeltdown")
        self.pushSpectreMeltdown = QtWidgets.QPushButton(parent=self.frame_SpectreMeltdown_2)
        self.pushSpectreMeltdown.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushSpectreMeltdown.setMinimumSize(QtCore.QSize(91, 31))
        self.pushSpectreMeltdown.setMaximumSize(QtCore.QSize(91, 31))
        self.pushSpectreMeltdown.setBaseSize(QtCore.QSize(0, 0))
        self.pushSpectreMeltdown.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushSpectreMeltdown.setObjectName("pushSpectreMeltdown")
        self.labelTextSpectreMeltdown = QtWidgets.QLabel(parent=self.frame_SpectreMeltdown_2)
        self.labelTextSpectreMeltdown.setGeometry(QtCore.QRect(30, 10, 161, 21))
        self.labelTextSpectreMeltdown.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextSpectreMeltdown.setObjectName("labelTextSpectreMeltdown")
        self.horizontalLayout_3.addWidget(self.frame_SpectreMeltdown_2)
        self.frame_svchosts = QtWidgets.QFrame(parent=self.frame)
        self.frame_svchosts.setGeometry(QtCore.QRect(10, 163, 921, 45))
        self.frame_svchosts.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_svchosts.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_svchosts {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_svchosts.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_svchosts.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_svchosts.setObjectName("frame_svchosts")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_svchosts)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_svchosts_2 = QtWidgets.QFrame(parent=self.frame_svchosts)
        self.frame_svchosts_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_svchosts_2.setStyleSheet("background-color: transparent;")
        self.frame_svchosts_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_svchosts_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_svchosts_2.setObjectName("frame_svchosts_2")
        self.labelsvchosts = QtWidgets.QLabel(parent=self.frame_svchosts_2)
        self.labelsvchosts.setGeometry(QtCore.QRect(580, 0, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelsvchosts.sizePolicy().hasHeightForWidth())
        self.labelsvchosts.setSizePolicy(sizePolicy)
        self.labelsvchosts.setMinimumSize(QtCore.QSize(70, 30))
        self.labelsvchosts.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelsvchosts.setText("")
        self.labelsvchosts.setObjectName("labelsvchosts")
        self.pushsvchosts = QtWidgets.QPushButton(parent=self.frame_svchosts_2)
        self.pushsvchosts.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushsvchosts.setMinimumSize(QtCore.QSize(91, 31))
        self.pushsvchosts.setMaximumSize(QtCore.QSize(91, 31))
        self.pushsvchosts.setBaseSize(QtCore.QSize(0, 0))
        self.pushsvchosts.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushsvchosts.setObjectName("pushsvchosts")
        self.labelTextsvchosts = QtWidgets.QLabel(parent=self.frame_svchosts_2)
        self.labelTextsvchosts.setGeometry(QtCore.QRect(30, 10, 161, 21))
        self.labelTextsvchosts.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextsvchosts.setObjectName("labelTextsvchosts")
        self.horizontalLayout_4.addWidget(self.frame_svchosts_2)
        self.frame_StorageUpdate = QtWidgets.QFrame(parent=self.frame)
        self.frame_StorageUpdate.setGeometry(QtCore.QRect(10, 214, 921, 45))
        self.frame_StorageUpdate.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_StorageUpdate.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_StorageUpdate {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_StorageUpdate.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_StorageUpdate.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_StorageUpdate.setObjectName("frame_StorageUpdate")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_StorageUpdate)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_StorageUpdate_2 = QtWidgets.QFrame(parent=self.frame_StorageUpdate)
        self.frame_StorageUpdate_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_StorageUpdate_2.setStyleSheet("background-color: transparent;")
        self.frame_StorageUpdate_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_StorageUpdate_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_StorageUpdate_2.setObjectName("frame_StorageUpdate_2")
        self.labelStorageUpdate = QtWidgets.QLabel(parent=self.frame_StorageUpdate_2)
        self.labelStorageUpdate.setGeometry(QtCore.QRect(579, 10, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelStorageUpdate.sizePolicy().hasHeightForWidth())
        self.labelStorageUpdate.setSizePolicy(sizePolicy)
        self.labelStorageUpdate.setMinimumSize(QtCore.QSize(70, 30))
        self.labelStorageUpdate.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelStorageUpdate.setText("")
        self.labelStorageUpdate.setObjectName("labelStorageUpdate")
        self.pushStorageUpdate = QtWidgets.QPushButton(parent=self.frame_StorageUpdate_2)
        self.pushStorageUpdate.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushStorageUpdate.setMinimumSize(QtCore.QSize(91, 31))
        self.pushStorageUpdate.setMaximumSize(QtCore.QSize(91, 31))
        self.pushStorageUpdate.setBaseSize(QtCore.QSize(0, 0))
        self.pushStorageUpdate.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushStorageUpdate.setObjectName("pushStorageUpdate")
        self.labelTextStorageUpdate = QtWidgets.QLabel(parent=self.frame_StorageUpdate_2)
        self.labelTextStorageUpdate.setGeometry(QtCore.QRect(30, 10, 161, 21))
        self.labelTextStorageUpdate.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextStorageUpdate.setObjectName("labelTextStorageUpdate")
        self.horizontalLayout_5.addWidget(self.frame_StorageUpdate_2)
        self.frame_UpdateNFS = QtWidgets.QFrame(parent=self.frame)
        self.frame_UpdateNFS.setGeometry(QtCore.QRect(10, 265, 921, 45))
        self.frame_UpdateNFS.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_UpdateNFS.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_UpdateNFS {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_UpdateNFS.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_UpdateNFS.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_UpdateNFS.setObjectName("frame_UpdateNFS")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_UpdateNFS)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_UpdateNFS_2 = QtWidgets.QFrame(parent=self.frame_UpdateNFS)
        self.frame_UpdateNFS_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_UpdateNFS_2.setStyleSheet("background-color: transparent;")
        self.frame_UpdateNFS_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_UpdateNFS_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_UpdateNFS_2.setObjectName("frame_UpdateNFS_2")
        self.labelUpdateNFS = QtWidgets.QLabel(parent=self.frame_UpdateNFS_2)
        self.labelUpdateNFS.setGeometry(QtCore.QRect(589, 10, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelUpdateNFS.sizePolicy().hasHeightForWidth())
        self.labelUpdateNFS.setSizePolicy(sizePolicy)
        self.labelUpdateNFS.setMinimumSize(QtCore.QSize(70, 30))
        self.labelUpdateNFS.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelUpdateNFS.setText("")
        self.labelUpdateNFS.setObjectName("labelUpdateNFS")
        self.pushUpdateNFS = QtWidgets.QPushButton(parent=self.frame_UpdateNFS_2)
        self.pushUpdateNFS.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushUpdateNFS.setMinimumSize(QtCore.QSize(91, 31))
        self.pushUpdateNFS.setMaximumSize(QtCore.QSize(91, 31))
        self.pushUpdateNFS.setBaseSize(QtCore.QSize(0, 0))
        self.pushUpdateNFS.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushUpdateNFS.setObjectName("pushUpdateNFS")
        self.labelTextUpdateNFS = QtWidgets.QLabel(parent=self.frame_UpdateNFS_2)
        self.labelTextUpdateNFS.setGeometry(QtCore.QRect(30, 10, 271, 21))
        self.labelTextUpdateNFS.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextUpdateNFS.setObjectName("labelTextUpdateNFS")
        self.horizontalLayout_6.addWidget(self.frame_UpdateNFS_2)
        self.frame_ConvNameFile83 = QtWidgets.QFrame(parent=self.frame)
        self.frame_ConvNameFile83.setGeometry(QtCore.QRect(10, 316, 921, 45))
        self.frame_ConvNameFile83.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_ConvNameFile83.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_ConvNameFile83 {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_ConvNameFile83.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ConvNameFile83.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ConvNameFile83.setObjectName("frame_ConvNameFile83")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_ConvNameFile83)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_ConvNameFile83_2 = QtWidgets.QFrame(parent=self.frame_ConvNameFile83)
        self.frame_ConvNameFile83_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_ConvNameFile83_2.setStyleSheet("background-color: transparent;")
        self.frame_ConvNameFile83_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ConvNameFile83_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ConvNameFile83_2.setObjectName("frame_ConvNameFile83_2")
        self.labelConvNameFile83 = QtWidgets.QLabel(parent=self.frame_ConvNameFile83_2)
        self.labelConvNameFile83.setGeometry(QtCore.QRect(569, 10, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelConvNameFile83.sizePolicy().hasHeightForWidth())
        self.labelConvNameFile83.setSizePolicy(sizePolicy)
        self.labelConvNameFile83.setMinimumSize(QtCore.QSize(70, 30))
        self.labelConvNameFile83.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelConvNameFile83.setText("")
        self.labelConvNameFile83.setObjectName("labelConvNameFile83")
        self.pushConvNameFile83 = QtWidgets.QPushButton(parent=self.frame_ConvNameFile83_2)
        self.pushConvNameFile83.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushConvNameFile83.setMinimumSize(QtCore.QSize(91, 31))
        self.pushConvNameFile83.setMaximumSize(QtCore.QSize(91, 31))
        self.pushConvNameFile83.setBaseSize(QtCore.QSize(0, 0))
        self.pushConvNameFile83.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushConvNameFile83.setObjectName("pushConvNameFile83")
        self.labelTextConvNameFile83 = QtWidgets.QLabel(parent=self.frame_ConvNameFile83_2)
        self.labelTextConvNameFile83.setGeometry(QtCore.QRect(30, 10, 271, 21))
        self.labelTextConvNameFile83.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextConvNameFile83.setObjectName("labelTextConvNameFile83")
        self.horizontalLayout_7.addWidget(self.frame_ConvNameFile83_2)
        self.frame_DiagnosricEvents = QtWidgets.QFrame(parent=self.frame)
        self.frame_DiagnosricEvents.setGeometry(QtCore.QRect(10, 367, 921, 45))
        self.frame_DiagnosricEvents.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_DiagnosricEvents.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_DiagnosricEvents {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_DiagnosricEvents.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_DiagnosricEvents.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_DiagnosricEvents.setObjectName("frame_DiagnosricEvents")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_DiagnosricEvents)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_DiagnosricEvents_2 = QtWidgets.QFrame(parent=self.frame_DiagnosricEvents)
        self.frame_DiagnosricEvents_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_DiagnosricEvents_2.setStyleSheet("background-color: transparent;")
        self.frame_DiagnosricEvents_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_DiagnosricEvents_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_DiagnosricEvents_2.setObjectName("frame_DiagnosricEvents_2")
        self.labelDiagnosricEvents = QtWidgets.QLabel(parent=self.frame_DiagnosricEvents_2)
        self.labelDiagnosricEvents.setGeometry(QtCore.QRect(589, 10, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelDiagnosricEvents.sizePolicy().hasHeightForWidth())
        self.labelDiagnosricEvents.setSizePolicy(sizePolicy)
        self.labelDiagnosricEvents.setMinimumSize(QtCore.QSize(70, 30))
        self.labelDiagnosricEvents.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelDiagnosricEvents.setText("")
        self.labelDiagnosricEvents.setObjectName("labelDiagnosricEvents")
        self.pushDiagnosricEvents = QtWidgets.QPushButton(parent=self.frame_DiagnosricEvents_2)
        self.pushDiagnosricEvents.setGeometry(QtCore.QRect(730, 10, 91, 31))
        self.pushDiagnosricEvents.setMinimumSize(QtCore.QSize(91, 31))
        self.pushDiagnosricEvents.setMaximumSize(QtCore.QSize(91, 31))
        self.pushDiagnosricEvents.setBaseSize(QtCore.QSize(0, 0))
        self.pushDiagnosricEvents.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushDiagnosricEvents.setObjectName("pushDiagnosricEvents")
        self.labelTextDiagnosricEvents = QtWidgets.QLabel(parent=self.frame_DiagnosricEvents_2)
        self.labelTextDiagnosricEvents.setGeometry(QtCore.QRect(30, 10, 271, 21))
        self.labelTextDiagnosricEvents.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.labelTextDiagnosricEvents.setObjectName("labelTextDiagnosricEvents")
        self.horizontalLayout_8.addWidget(self.frame_DiagnosricEvents_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Twics)
        QtCore.QMetaObject.connectSlotsByName(Twics)

    def retranslateUi(self, Twics):
        _translate = QtCore.QCoreApplication.translate
        Twics.setWindowTitle(_translate("Twics", "Form"))
        self.pushSystemResponsiveness.setText(_translate("Twics", "Выбрать"))
        self.labelTextSystemResponsiveness.setText(_translate("Twics", "SystemResponsiveness"))
        self.pushWin32PrioritySeparation.setText(_translate("Twics", "Выбрать"))
        self.labelTextWin32PrioritySeparation.setText(_translate("Twics", "Win32PrioritySeparation"))
        self.pushSpectreMeltdown.setText(_translate("Twics", "Выбрать"))
        self.labelTextSpectreMeltdown.setText(_translate("Twics", "Spectre, Meltdown"))
        self.pushsvchosts.setText(_translate("Twics", "Выбрать"))
        self.labelTextsvchosts.setText(_translate("Twics", "Группировка служб"))
        self.pushStorageUpdate.setText(_translate("Twics", "Выбрать"))
        self.labelTextStorageUpdate.setText(_translate("Twics", "Хранилище обновлений"))
        self.pushUpdateNFS.setText(_translate("Twics", "Выбрать"))
        self.labelTextUpdateNFS.setText(_translate("Twics", "Обновление последнего доступа NFS"))
        self.pushConvNameFile83.setText(_translate("Twics", "Выбрать"))
        self.labelTextConvNameFile83.setText(_translate("Twics", "Ковертация  имен файлов 8.3"))
        self.pushDiagnosricEvents.setText(_translate("Twics", "Выбрать"))
        self.labelTextDiagnosricEvents.setText(_translate("Twics", "Диагностические события"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Twics = QtWidgets.QWidget()
    ui = Ui_Twics()
    ui.setupUi(Twics)
    Twics.show()
    sys.exit(app.exec())
