# Form implementation generated from reading ui file '.\WindowsCleaning.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowsCleaning(object):
    def setupUi(self, WindowsCleaning):
        WindowsCleaning.setObjectName("WindowsCleaning")
        WindowsCleaning.resize(1114, 731)
        WindowsCleaning.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(parent=WindowsCleaning)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1015, 602))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(820, 20, 120, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 991, 581))
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
"*{\n"
"margin:0\n"
"\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #161A1E;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #34373b;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:#161A1E;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #161A1E;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 975, 670))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 670))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(10, 20, 951, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_AntivirusWindows = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows.setObjectName("frame_AntivirusWindows")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget_AntivirusWindows = QtWidgets.QListWidget(parent=self.frame_AntivirusWindows)
        self.listWidget_AntivirusWindows.setMaximumSize(QtCore.QSize(700, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.listWidget_AntivirusWindows.setFont(font)
        self.listWidget_AntivirusWindows.setStyleSheet("QListWidget::item {\n"
"    border-bottom: 1px solid rgba(85,98,112,255);;\n"
"}\n"
"\n"
"")
        self.listWidget_AntivirusWindows.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_AntivirusWindows.setAutoScroll(True)
        self.listWidget_AntivirusWindows.setObjectName("listWidget_AntivirusWindows")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_AntivirusWindows.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget_AntivirusWindows)
        self.frame_1 = QtWidgets.QFrame(parent=self.frame_AntivirusWindows)
        self.frame_1.setStyleSheet("background-color: transparent;")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_1.setObjectName("frame_1")
        self.pushClearTemporaryFiles = QtWidgets.QPushButton(parent=self.frame_1)
        self.pushClearTemporaryFiles.setGeometry(QtCore.QRect(150, 0, 75, 23))
        self.pushClearTemporaryFiles.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black")
        self.pushClearTemporaryFiles.setObjectName("pushClearTemporaryFiles")
        self.labelClearTemporaryFiles = QtWidgets.QLabel(parent=self.frame_1)
        self.labelClearTemporaryFiles.setGeometry(QtCore.QRect(20, 5, 81, 21))
        self.labelClearTemporaryFiles.setText("")
        self.labelClearTemporaryFiles.setObjectName("labelClearTemporaryFiles")
        self.horizontalLayout.addWidget(self.frame_1)
        self.verticalLayout.addWidget(self.frame_AntivirusWindows)
        self.frame_AntivirusWindows_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_3.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_3.setObjectName("frame_AntivirusWindows_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listWidget_AntivirusWindows_2 = QtWidgets.QListWidget(parent=self.frame_AntivirusWindows_3)
        self.listWidget_AntivirusWindows_2.setMaximumSize(QtCore.QSize(700, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.listWidget_AntivirusWindows_2.setFont(font)
        self.listWidget_AntivirusWindows_2.setStyleSheet("QListWidget::item {\n"
"    border-bottom: 1px solid rgba(85,98,112,255);;\n"
"}\n"
"\n"
"")
        self.listWidget_AntivirusWindows_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_AntivirusWindows_2.setAutoScroll(True)
        self.listWidget_AntivirusWindows_2.setObjectName("listWidget_AntivirusWindows_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_AntivirusWindows_2.addItem(item)
        self.horizontalLayout_3.addWidget(self.listWidget_AntivirusWindows_2)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_AntivirusWindows_3)
        self.frame_2.setStyleSheet("background-color: transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushClearthumbnailcache = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushClearthumbnailcache.setGeometry(QtCore.QRect(150, 0, 75, 23))
        self.pushClearthumbnailcache.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black")
        self.pushClearthumbnailcache.setObjectName("pushClearthumbnailcache")
        self.labelClearthumbnailcache = QtWidgets.QLabel(parent=self.frame_2)
        self.labelClearthumbnailcache.setGeometry(QtCore.QRect(20, 5, 81, 21))
        self.labelClearthumbnailcache.setText("")
        self.labelClearthumbnailcache.setObjectName("labelClearthumbnailcache")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_3)
        self.frame_AntivirusWindows_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_4.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_4.setObjectName("frame_AntivirusWindows_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget_AntivirusWindows_3 = QtWidgets.QListWidget(parent=self.frame_AntivirusWindows_4)
        self.listWidget_AntivirusWindows_3.setMaximumSize(QtCore.QSize(700, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.listWidget_AntivirusWindows_3.setFont(font)
        self.listWidget_AntivirusWindows_3.setStyleSheet("QListWidget::item {\n"
"    border-bottom: 1px solid rgba(85,98,112,255);;\n"
"}\n"
"\n"
"")
        self.listWidget_AntivirusWindows_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_AntivirusWindows_3.setAutoScroll(True)
        self.listWidget_AntivirusWindows_3.setObjectName("listWidget_AntivirusWindows_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_AntivirusWindows_3.addItem(item)
        self.horizontalLayout_4.addWidget(self.listWidget_AntivirusWindows_3)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_AntivirusWindows_4)
        self.frame_3.setStyleSheet("background-color: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushClearinstallationlogfiles = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushClearinstallationlogfiles.setGeometry(QtCore.QRect(150, 0, 75, 23))
        self.pushClearinstallationlogfiles.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black")
        self.pushClearinstallationlogfiles.setObjectName("pushClearinstallationlogfiles")
        self.labelClearinstallationlogfiles = QtWidgets.QLabel(parent=self.frame_3)
        self.labelClearinstallationlogfiles.setGeometry(QtCore.QRect(20, 5, 81, 21))
        self.labelClearinstallationlogfiles.setText("")
        self.labelClearinstallationlogfiles.setObjectName("labelClearinstallationlogfiles")
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_4)
        self.frame_AntivirusWindows_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_5.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_5.setObjectName("frame_AntivirusWindows_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidget_AntivirusWindows_4 = QtWidgets.QListWidget(parent=self.frame_AntivirusWindows_5)
        self.listWidget_AntivirusWindows_4.setMaximumSize(QtCore.QSize(700, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.listWidget_AntivirusWindows_4.setFont(font)
        self.listWidget_AntivirusWindows_4.setStyleSheet("QListWidget::item {\n"
"    border-bottom: 1px solid rgba(85,98,112,255);;\n"
"}\n"
"\n"
"")
        self.listWidget_AntivirusWindows_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_AntivirusWindows_4.setAutoScroll(True)
        self.listWidget_AntivirusWindows_4.setObjectName("listWidget_AntivirusWindows_4")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_AntivirusWindows_4.addItem(item)
        self.horizontalLayout_5.addWidget(self.listWidget_AntivirusWindows_4)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_AntivirusWindows_5)
        self.frame_4.setStyleSheet("background-color: transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushDownloadedprogramfiles_2 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushDownloadedprogramfiles_2.setGeometry(QtCore.QRect(150, 0, 75, 23))
        self.pushDownloadedprogramfiles_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black")
        self.pushDownloadedprogramfiles_2.setObjectName("pushDownloadedprogramfiles_2")
        self.labelDownloadedprogramfiles = QtWidgets.QLabel(parent=self.frame_4)
        self.labelDownloadedprogramfiles.setGeometry(QtCore.QRect(20, 5, 81, 21))
        self.labelDownloadedprogramfiles.setText("")
        self.labelDownloadedprogramfiles.setObjectName("labelDownloadedprogramfiles")
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_5)
        self.frame_AntivirusWindows_6 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_6.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_6.setObjectName("frame_AntivirusWindows_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.listWidget_AntivirusWindows_5 = QtWidgets.QListWidget(parent=self.frame_AntivirusWindows_6)
        self.listWidget_AntivirusWindows_5.setMaximumSize(QtCore.QSize(700, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.listWidget_AntivirusWindows_5.setFont(font)
        self.listWidget_AntivirusWindows_5.setStyleSheet("QListWidget::item {\n"
"    border-bottom: 1px solid rgba(85,98,112,255);;\n"
"}\n"
"\n"
"")
        self.listWidget_AntivirusWindows_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_AntivirusWindows_5.setAutoScroll(True)
        self.listWidget_AntivirusWindows_5.setObjectName("listWidget_AntivirusWindows_5")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_AntivirusWindows_5.addItem(item)
        self.horizontalLayout_6.addWidget(self.listWidget_AntivirusWindows_5)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_AntivirusWindows_6)
        self.frame_5.setStyleSheet("background-color: transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushCleardeliveryoptimizationfiles = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushCleardeliveryoptimizationfiles.setGeometry(QtCore.QRect(150, 0, 75, 23))
        self.pushCleardeliveryoptimizationfiles.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black")
        self.pushCleardeliveryoptimizationfiles.setObjectName("pushCleardeliveryoptimizationfiles")
        self.labelCleardeliveryoptimizationfiles = QtWidgets.QLabel(parent=self.frame_5)
        self.labelCleardeliveryoptimizationfiles.setGeometry(QtCore.QRect(20, 5, 81, 21))
        self.labelCleardeliveryoptimizationfiles.setText("")
        self.labelCleardeliveryoptimizationfiles.setObjectName("labelCleardeliveryoptimizationfiles")
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_6)
        self.frame_AntivirusWindows_7 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_7.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_7.setObjectName("frame_AntivirusWindows_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.listWidget_AntivirusWindows_6 = QtWidgets.QListWidget(parent=self.frame_AntivirusWindows_7)
        self.listWidget_AntivirusWindows_6.setMaximumSize(QtCore.QSize(700, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.listWidget_AntivirusWindows_6.setFont(font)
        self.listWidget_AntivirusWindows_6.setStyleSheet("QListWidget::item {\n"
"    border-bottom: 1px solid rgba(85,98,112,255);;\n"
"}\n"
"\n"
"")
        self.listWidget_AntivirusWindows_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_AntivirusWindows_6.setAutoScroll(True)
        self.listWidget_AntivirusWindows_6.setObjectName("listWidget_AntivirusWindows_6")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_AntivirusWindows_6.addItem(item)
        self.horizontalLayout_7.addWidget(self.listWidget_AntivirusWindows_6)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_AntivirusWindows_7)
        self.frame_6.setStyleSheet("background-color: transparent;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushClearTemporaryFiles_6 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushClearTemporaryFiles_6.setGeometry(QtCore.QRect(150, 0, 75, 23))
        self.pushClearTemporaryFiles_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black")
        self.pushClearTemporaryFiles_6.setObjectName("pushClearTemporaryFiles_6")
        self.labelClearTemporaryFiles_6 = QtWidgets.QLabel(parent=self.frame_6)
        self.labelClearTemporaryFiles_6.setGeometry(QtCore.QRect(20, 5, 81, 21))
        self.labelClearTemporaryFiles_6.setText("")
        self.labelClearTemporaryFiles_6.setObjectName("labelClearTemporaryFiles_6")
        self.horizontalLayout_7.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_7)
        self.frame_AntivirusWindows_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_2.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_2.setObjectName("frame_AntivirusWindows_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_2)
        self.frame_AutoUpdateMaps = QtWidgets.QFrame(parent=self.frame)
        self.frame_AutoUpdateMaps.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AutoUpdateMaps.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AutoUpdateMaps.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AutoUpdateMaps.setObjectName("frame_AutoUpdateMaps")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_AutoUpdateMaps)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout.addWidget(self.frame_AutoUpdateMaps)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_AntivirusWindows_8 = QtWidgets.QFrame(parent=WindowsCleaning)
        self.frame_AntivirusWindows_8.setGeometry(QtCore.QRect(100, 650, 949, 32))
        self.frame_AntivirusWindows_8.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_8.setObjectName("frame_AntivirusWindows_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")

        self.retranslateUi(WindowsCleaning)
        QtCore.QMetaObject.connectSlotsByName(WindowsCleaning)

    def retranslateUi(self, WindowsCleaning):
        _translate = QtCore.QCoreApplication.translate
        WindowsCleaning.setWindowTitle(_translate("WindowsCleaning", "Form"))
        __sortingEnabled = self.listWidget_AntivirusWindows.isSortingEnabled()
        self.listWidget_AntivirusWindows.setSortingEnabled(False)
        item = self.listWidget_AntivirusWindows.item(0)
        item.setText(_translate("WindowsCleaning", "Временные файлы"))
        self.listWidget_AntivirusWindows.setSortingEnabled(__sortingEnabled)
        self.pushClearTemporaryFiles.setText(_translate("WindowsCleaning", "Очистка"))
        __sortingEnabled = self.listWidget_AntivirusWindows_2.isSortingEnabled()
        self.listWidget_AntivirusWindows_2.setSortingEnabled(False)
        item = self.listWidget_AntivirusWindows_2.item(0)
        item.setText(_translate("WindowsCleaning", "Кэш экскизов"))
        self.listWidget_AntivirusWindows_2.setSortingEnabled(__sortingEnabled)
        self.pushClearthumbnailcache.setText(_translate("WindowsCleaning", "Очистка"))
        __sortingEnabled = self.listWidget_AntivirusWindows_3.isSortingEnabled()
        self.listWidget_AntivirusWindows_3.setSortingEnabled(False)
        item = self.listWidget_AntivirusWindows_3.item(0)
        item.setText(_translate("WindowsCleaning", "Файлы журнала установок"))
        self.listWidget_AntivirusWindows_3.setSortingEnabled(__sortingEnabled)
        self.pushClearinstallationlogfiles.setText(_translate("WindowsCleaning", "Очистка"))
        __sortingEnabled = self.listWidget_AntivirusWindows_4.isSortingEnabled()
        self.listWidget_AntivirusWindows_4.setSortingEnabled(False)
        item = self.listWidget_AntivirusWindows_4.item(0)
        item.setText(_translate("WindowsCleaning", "Загруженные файлы программ"))
        self.listWidget_AntivirusWindows_4.setSortingEnabled(__sortingEnabled)
        self.pushDownloadedprogramfiles_2.setText(_translate("WindowsCleaning", "Очистка"))
        __sortingEnabled = self.listWidget_AntivirusWindows_5.isSortingEnabled()
        self.listWidget_AntivirusWindows_5.setSortingEnabled(False)
        item = self.listWidget_AntivirusWindows_5.item(0)
        item.setText(_translate("WindowsCleaning", "Временные файлы"))
        self.listWidget_AntivirusWindows_5.setSortingEnabled(__sortingEnabled)
        self.pushCleardeliveryoptimizationfiles.setText(_translate("WindowsCleaning", "Очистка"))
        __sortingEnabled = self.listWidget_AntivirusWindows_6.isSortingEnabled()
        self.listWidget_AntivirusWindows_6.setSortingEnabled(False)
        item = self.listWidget_AntivirusWindows_6.item(0)
        item.setText(_translate("WindowsCleaning", "Временные файлы"))
        self.listWidget_AntivirusWindows_6.setSortingEnabled(__sortingEnabled)
        self.pushClearTemporaryFiles_6.setText(_translate("WindowsCleaning", "Очистка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowsCleaning = QtWidgets.QWidget()
    ui = Ui_WindowsCleaning()
    ui.setupUi(WindowsCleaning)
    WindowsCleaning.show()
    sys.exit(app.exec())
