# Form implementation generated from reading ui file '.\WindowsCleaning.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowsCleaning(object):
    def setupUi(self, WindowsCleaning):
        WindowsCleaning.setObjectName("WindowsCleaning")
        WindowsCleaning.resize(1114, 731)
        WindowsCleaning.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(parent=WindowsCleaning)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1015, 602))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(820, 20, 120, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 991, 581))
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
"*{\n"
"margin:0\n"
"\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #161A1E;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #34373b;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(119, 122, 126);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:#161A1E;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #161A1E;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 975, 670))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 670))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(10, 20, 961, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_ClearTemporaryFiles = QtWidgets.QFrame(parent=self.frame)
        self.frame_ClearTemporaryFiles.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_ClearTemporaryFiles.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_ClearTemporaryFiles {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_ClearTemporaryFiles.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ClearTemporaryFiles.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ClearTemporaryFiles.setObjectName("frame_ClearTemporaryFiles")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_ClearTemporaryFiles)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_1 = QtWidgets.QFrame(parent=self.frame_ClearTemporaryFiles)
        self.frame_1.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_1.setStyleSheet("background-color: transparent;")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_1.setObjectName("frame_1")
        self.labelClearTemporaryFiles = QtWidgets.QLabel(parent=self.frame_1)
        self.labelClearTemporaryFiles.setGeometry(QtCore.QRect(760, 10, 70, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelClearTemporaryFiles.sizePolicy().hasHeightForWidth())
        self.labelClearTemporaryFiles.setSizePolicy(sizePolicy)
        self.labelClearTemporaryFiles.setMinimumSize(QtCore.QSize(70, 30))
        self.labelClearTemporaryFiles.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelClearTemporaryFiles.setText("")
        self.labelClearTemporaryFiles.setObjectName("labelClearTemporaryFiles")
        self.pushClearTemporaryFiles = QtWidgets.QPushButton(parent=self.frame_1)
        self.pushClearTemporaryFiles.setGeometry(QtCore.QRect(850, 10, 91, 31))
        self.pushClearTemporaryFiles.setMinimumSize(QtCore.QSize(91, 31))
        self.pushClearTemporaryFiles.setMaximumSize(QtCore.QSize(91, 31))
        self.pushClearTemporaryFiles.setBaseSize(QtCore.QSize(0, 0))
        self.pushClearTemporaryFiles.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushClearTemporaryFiles.setObjectName("pushClearTemporaryFiles")
        self.label = QtWidgets.QLabel(parent=self.frame_1)
        self.label.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.frame_1)
        self.verticalLayout.addWidget(self.frame_ClearTemporaryFiles)
        self.frame_AntivirusWindows_8 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_8.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_8.setObjectName("frame_AntivirusWindows_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_8)
        self.frame_Clearthumbnailcache = QtWidgets.QFrame(parent=self.frame)
        self.frame_Clearthumbnailcache.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_Clearthumbnailcache.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_Clearthumbnailcache.setStyleSheet("/* styles.qss */\n"
"\n"
"#frame_Clearthumbnailcache {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_Clearthumbnailcache.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Clearthumbnailcache.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Clearthumbnailcache.setObjectName("frame_Clearthumbnailcache")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_Clearthumbnailcache)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_Clearthumbnailcache)
        self.frame_2.setStyleSheet("background-color: transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushClearthumbnailcache = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushClearthumbnailcache.setGeometry(QtCore.QRect(850, 10, 91, 31))
        self.pushClearthumbnailcache.setMaximumSize(QtCore.QSize(91, 31))
        self.pushClearthumbnailcache.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushClearthumbnailcache.setObjectName("pushClearthumbnailcache")
        self.labelClearthumbnailcache = QtWidgets.QLabel(parent=self.frame_2)
        self.labelClearthumbnailcache.setGeometry(QtCore.QRect(750, 10, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelClearthumbnailcache.sizePolicy().hasHeightForWidth())
        self.labelClearthumbnailcache.setSizePolicy(sizePolicy)
        self.labelClearthumbnailcache.setMinimumSize(QtCore.QSize(70, 30))
        self.labelClearthumbnailcache.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelClearthumbnailcache.setText("")
        self.labelClearthumbnailcache.setObjectName("labelClearthumbnailcache")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 111, 16))
        self.label_2.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_Clearthumbnailcache)
        self.frame_AntivirusWindows_11 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_11.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_11.setObjectName("frame_AntivirusWindows_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_11)
        self.frame_Clearinstallationlogfiles = QtWidgets.QFrame(parent=self.frame)
        self.frame_Clearinstallationlogfiles.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_Clearinstallationlogfiles.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_Clearinstallationlogfiles.setStyleSheet("\n"
"/* styles.qss */\n"
"\n"
"#frame_Clearinstallationlogfiles {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_Clearinstallationlogfiles.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Clearinstallationlogfiles.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Clearinstallationlogfiles.setObjectName("frame_Clearinstallationlogfiles")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_Clearinstallationlogfiles)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_Clearinstallationlogfiles)
        self.frame_3.setStyleSheet("background-color: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushClearinstallationlogfiles = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushClearinstallationlogfiles.setGeometry(QtCore.QRect(850, 0, 91, 31))
        self.pushClearinstallationlogfiles.setMinimumSize(QtCore.QSize(91, 31))
        self.pushClearinstallationlogfiles.setMaximumSize(QtCore.QSize(91, 31))
        self.pushClearinstallationlogfiles.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushClearinstallationlogfiles.setObjectName("pushClearinstallationlogfiles")
        self.labelClearinstallationlogfiles = QtWidgets.QLabel(parent=self.frame_3)
        self.labelClearinstallationlogfiles.setGeometry(QtCore.QRect(750, 10, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelClearinstallationlogfiles.sizePolicy().hasHeightForWidth())
        self.labelClearinstallationlogfiles.setSizePolicy(sizePolicy)
        self.labelClearinstallationlogfiles.setMinimumSize(QtCore.QSize(70, 30))
        self.labelClearinstallationlogfiles.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelClearinstallationlogfiles.setText("")
        self.labelClearinstallationlogfiles.setObjectName("labelClearinstallationlogfiles")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 181, 21))
        self.label_3.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_Clearinstallationlogfiles)
        self.frame_AntivirusWindows_12 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_12.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_12.setObjectName("frame_AntivirusWindows_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_12)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_12)
        self.frame_ClearDownloadedprogramfiles = QtWidgets.QFrame(parent=self.frame)
        self.frame_ClearDownloadedprogramfiles.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_ClearDownloadedprogramfiles.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_ClearDownloadedprogramfiles.setStyleSheet("\n"
"/* styles.qss */\n"
"\n"
"#frame_ClearDownloadedprogramfiles {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_ClearDownloadedprogramfiles.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ClearDownloadedprogramfiles.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ClearDownloadedprogramfiles.setObjectName("frame_ClearDownloadedprogramfiles")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_ClearDownloadedprogramfiles)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_ClearDownloadedprogramfiles)
        self.frame_4.setStyleSheet("background-color: transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushClearDownloadedprogramfiles = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushClearDownloadedprogramfiles.setGeometry(QtCore.QRect(850, 10, 91, 31))
        self.pushClearDownloadedprogramfiles.setMinimumSize(QtCore.QSize(91, 31))
        self.pushClearDownloadedprogramfiles.setMaximumSize(QtCore.QSize(91, 31))
        self.pushClearDownloadedprogramfiles.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushClearDownloadedprogramfiles.setObjectName("pushClearDownloadedprogramfiles")
        self.labelClearDownloadedprogramfiles = QtWidgets.QLabel(parent=self.frame_4)
        self.labelClearDownloadedprogramfiles.setGeometry(QtCore.QRect(720, 10, 101, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelClearDownloadedprogramfiles.sizePolicy().hasHeightForWidth())
        self.labelClearDownloadedprogramfiles.setSizePolicy(sizePolicy)
        self.labelClearDownloadedprogramfiles.setMinimumSize(QtCore.QSize(70, 30))
        self.labelClearDownloadedprogramfiles.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelClearDownloadedprogramfiles.setText("")
        self.labelClearDownloadedprogramfiles.setObjectName("labelClearDownloadedprogramfiles")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 201, 20))
        self.label_4.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_ClearDownloadedprogramfiles)
        self.frame_AntivirusWindows_13 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_13.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_13.setObjectName("frame_AntivirusWindows_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_13)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_13)
        self.frame_ClearDeliveryOptimizationFiles = QtWidgets.QFrame(parent=self.frame)
        self.frame_ClearDeliveryOptimizationFiles.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frame_ClearDeliveryOptimizationFiles.setStyleSheet("\n"
"/* styles.qss */\n"
"\n"
"#frame_ClearDeliveryOptimizationFiles {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_ClearDeliveryOptimizationFiles.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ClearDeliveryOptimizationFiles.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ClearDeliveryOptimizationFiles.setObjectName("frame_ClearDeliveryOptimizationFiles")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_ClearDeliveryOptimizationFiles)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_ClearDeliveryOptimizationFiles)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_5.setStyleSheet("background-color: transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushClearDeliveryOptimizationFiles = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushClearDeliveryOptimizationFiles.setGeometry(QtCore.QRect(850, 10, 91, 31))
        self.pushClearDeliveryOptimizationFiles.setMinimumSize(QtCore.QSize(91, 31))
        self.pushClearDeliveryOptimizationFiles.setMaximumSize(QtCore.QSize(91, 31))
        self.pushClearDeliveryOptimizationFiles.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushClearDeliveryOptimizationFiles.setObjectName("pushClearDeliveryOptimizationFiles")
        self.labelClearDeliveryOptimizationFiles = QtWidgets.QLabel(parent=self.frame_5)
        self.labelClearDeliveryOptimizationFiles.setGeometry(QtCore.QRect(750, 10, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelClearDeliveryOptimizationFiles.sizePolicy().hasHeightForWidth())
        self.labelClearDeliveryOptimizationFiles.setSizePolicy(sizePolicy)
        self.labelClearDeliveryOptimizationFiles.setMinimumSize(QtCore.QSize(70, 30))
        self.labelClearDeliveryOptimizationFiles.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelClearDeliveryOptimizationFiles.setText("")
        self.labelClearDeliveryOptimizationFiles.setObjectName("labelClearDeliveryOptimizationFiles")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 201, 21))
        self.label_5.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_ClearDeliveryOptimizationFiles)
        self.frame_AntivirusWindows_14 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_14.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_14.setObjectName("frame_AntivirusWindows_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_14)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_14)
        self.frame_ClearDirectXShaderCache = QtWidgets.QFrame(parent=self.frame)
        self.frame_ClearDirectXShaderCache.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_ClearDirectXShaderCache.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_ClearDirectXShaderCache.setStyleSheet("\n"
"/* styles.qss */\n"
"\n"
"#frame_ClearDirectXShaderCache {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_ClearDirectXShaderCache.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ClearDirectXShaderCache.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ClearDirectXShaderCache.setObjectName("frame_ClearDirectXShaderCache")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_ClearDirectXShaderCache)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_ClearDirectXShaderCache)
        self.frame_6.setStyleSheet("background-color: transparent;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushClearDirectXShaderCache = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushClearDirectXShaderCache.setGeometry(QtCore.QRect(850, 0, 91, 31))
        self.pushClearDirectXShaderCache.setMinimumSize(QtCore.QSize(91, 31))
        self.pushClearDirectXShaderCache.setMaximumSize(QtCore.QSize(91, 31))
        self.pushClearDirectXShaderCache.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushClearDirectXShaderCache.setObjectName("pushClearDirectXShaderCache")
        self.labelClearDirectXShaderCache = QtWidgets.QLabel(parent=self.frame_6)
        self.labelClearDirectXShaderCache.setGeometry(QtCore.QRect(750, 10, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelClearDirectXShaderCache.sizePolicy().hasHeightForWidth())
        self.labelClearDirectXShaderCache.setSizePolicy(sizePolicy)
        self.labelClearDirectXShaderCache.setMinimumSize(QtCore.QSize(70, 30))
        self.labelClearDirectXShaderCache.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelClearDirectXShaderCache.setText("")
        self.labelClearDirectXShaderCache.setObjectName("labelClearDirectXShaderCache")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 181, 16))
        self.label_6.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_ClearDirectXShaderCache)
        self.frame_AntivirusWindows_15 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_15.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_15.setObjectName("frame_AntivirusWindows_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_15)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_15)
        self.frame_ClearFileSysremError = QtWidgets.QFrame(parent=self.frame)
        self.frame_ClearFileSysremError.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_ClearFileSysremError.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_ClearFileSysremError.setStyleSheet("\n"
"/* styles.qss */\n"
"\n"
"#frame_ClearFileSysremError {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_ClearFileSysremError.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ClearFileSysremError.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ClearFileSysremError.setObjectName("frame_ClearFileSysremError")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_ClearFileSysremError)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_ClearFileSysremError)
        self.frame_7.setStyleSheet("background-color: transparent;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushClearFileSysremError = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushClearFileSysremError.setGeometry(QtCore.QRect(850, 10, 91, 31))
        self.pushClearFileSysremError.setMinimumSize(QtCore.QSize(91, 31))
        self.pushClearFileSysremError.setMaximumSize(QtCore.QSize(91, 31))
        self.pushClearFileSysremError.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushClearFileSysremError.setObjectName("pushClearFileSysremError")
        self.labelClearFileSysremError = QtWidgets.QLabel(parent=self.frame_7)
        self.labelClearFileSysremError.setGeometry(QtCore.QRect(760, 10, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelClearFileSysremError.sizePolicy().hasHeightForWidth())
        self.labelClearFileSysremError.setSizePolicy(sizePolicy)
        self.labelClearFileSysremError.setMinimumSize(QtCore.QSize(70, 30))
        self.labelClearFileSysremError.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelClearFileSysremError.setText("")
        self.labelClearFileSysremError.setObjectName("labelClearFileSysremError")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 181, 16))
        self.label_7.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_ClearFileSysremError)
        self.frame_AntivirusWindows_16 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_16.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_16.setObjectName("frame_AntivirusWindows_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_16)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_16)
        self.frame_ClearChkDsk = QtWidgets.QFrame(parent=self.frame)
        self.frame_ClearChkDsk.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_ClearChkDsk.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_ClearChkDsk.setStyleSheet("\n"
"/* styles.qss */\n"
"\n"
"#frame_ClearChkDsk {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px; /* Установите значение по вашему усмотрению для достижения овальной формы */\n"
"}\n"
"")
        self.frame_ClearChkDsk.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ClearChkDsk.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ClearChkDsk.setObjectName("frame_ClearChkDsk")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_ClearChkDsk)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_ClearChkDsk)
        self.frame_8.setStyleSheet("background-color: transparent;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushClearChkDsk = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushClearChkDsk.setGeometry(QtCore.QRect(850, 10, 91, 31))
        self.pushClearChkDsk.setMinimumSize(QtCore.QSize(91, 31))
        self.pushClearChkDsk.setMaximumSize(QtCore.QSize(91, 31))
        self.pushClearChkDsk.setStyleSheet("/* styles.qss */\n"
"\n"
"QPushButton {\n"
"    background-color: #161A1E;\n"
"    border-radius: 15px;\n"
"    color: white; /* Установите цвет текста */\n"
"    font-size: 11px; /* Установите размер шрифта */\n"
"    padding: 10px 20px; /* Установите отступы */\n"
"    border: 1px solid white; /* Уменьшаем толщину обводки до 1 пикселя */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C3236;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"")
        self.pushClearChkDsk.setObjectName("pushClearChkDsk")
        self.labelClearChkDsk = QtWidgets.QLabel(parent=self.frame_8)
        self.labelClearChkDsk.setGeometry(QtCore.QRect(750, 10, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelClearChkDsk.sizePolicy().hasHeightForWidth())
        self.labelClearChkDsk.setSizePolicy(sizePolicy)
        self.labelClearChkDsk.setMinimumSize(QtCore.QSize(70, 30))
        self.labelClearChkDsk.setStyleSheet("color: white; /* Установите цвет текста в белый */\n"
"font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"margin-top: 5px; /* Опустить текст на 10 пикселей вниз */")
        self.labelClearChkDsk.setText("")
        self.labelClearChkDsk.setObjectName("labelClearChkDsk")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 161, 21))
        self.label_8.setStyleSheet("/* styles.qss */\n"
"\n"
"QLabel {\n"
"    color: white; /* Установите цвет текста в белый */\n"
"    font-size: 14px; /* Установите размер шрифта в 14 пикселей */\n"
"    font-family: \"Times New Roman\"; /* Установите тип шрифта по вашему выбору */\n"
"    font-weight: bold; /* Установите жирность шрифта (если нужно) */\n"
"    margin-top: 5px; /* Опустить текст на 10 пикселей вниз */\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_ClearChkDsk)
        self.frame_AntivirusWindows_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_AntivirusWindows_2.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AntivirusWindows_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AntivirusWindows_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AntivirusWindows_2.setObjectName("frame_AntivirusWindows_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_AntivirusWindows_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.frame_AntivirusWindows_2)
        self.frame_AutoUpdateMaps = QtWidgets.QFrame(parent=self.frame)
        self.frame_AutoUpdateMaps.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_AutoUpdateMaps.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AutoUpdateMaps.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AutoUpdateMaps.setObjectName("frame_AutoUpdateMaps")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_AutoUpdateMaps)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout.addWidget(self.frame_AutoUpdateMaps)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(WindowsCleaning)
        QtCore.QMetaObject.connectSlotsByName(WindowsCleaning)

    def retranslateUi(self, WindowsCleaning):
        _translate = QtCore.QCoreApplication.translate
        WindowsCleaning.setWindowTitle(_translate("WindowsCleaning", "Form"))
        self.pushClearTemporaryFiles.setText(_translate("WindowsCleaning", "Очистка"))
        self.label.setText(_translate("WindowsCleaning", "Временные файлы"))
        self.pushClearthumbnailcache.setText(_translate("WindowsCleaning", "Очистка"))
        self.label_2.setText(_translate("WindowsCleaning", "Кэш экскизов"))
        self.pushClearinstallationlogfiles.setText(_translate("WindowsCleaning", "Очистка"))
        self.label_3.setText(_translate("WindowsCleaning", "Файлы журнала установок"))
        self.pushClearDownloadedprogramfiles.setText(_translate("WindowsCleaning", "Очистка"))
        self.label_4.setText(_translate("WindowsCleaning", "Загруженные файлы программ"))
        self.pushClearDeliveryOptimizationFiles.setText(_translate("WindowsCleaning", "Очистка"))
        self.label_5.setText(_translate("WindowsCleaning", "Файлы оптимизации доставки"))
        self.pushClearDirectXShaderCache.setText(_translate("WindowsCleaning", "Очистка"))
        self.label_6.setText(_translate("WindowsCleaning", "DirectX Shader Cache"))
        self.pushClearFileSysremError.setText(_translate("WindowsCleaning", "Очистка"))
        self.label_7.setText(_translate("WindowsCleaning", "Фаилы системных ошибок"))
        self.pushClearChkDsk.setText(_translate("WindowsCleaning", "Очистка"))
        self.label_8.setText(_translate("WindowsCleaning", "Старые файлы ChkDsk"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowsCleaning = QtWidgets.QWidget()
    ui = Ui_WindowsCleaning()
    ui.setupUi(WindowsCleaning)
    WindowsCleaning.show()
    sys.exit(app.exec())
